using System.Text;
using Sgpa.Domain.Metadata;

// Genera DOS archivos a partir del metadata (reflexiona Sgpa.Domain; sin DB):
//  1) EntityNavigation.g.cs  -> propiedades de navegación (referencia N-a-1 + colección 1-a-N) como partials,
//     para que el ObjectDataSource muestre el grafo de objetos (experiencia XPO/EF).
//  2) ReportNavMap.g.cs      -> mapa tipo->relaciones (propName, kind, tipo remoto, columna de join) para que
//     el loader de runtime pueble cada nav prop SIN re-derivar la convención (nombres siempre alineados).
//
// La FK por convención (columna cuyo nombre == clave simple de otra entidad) se resuelve SÓLO entre tablas
// "reales" (ReportableTables.IsDefault), excluyendo temporales/XAF/working tables que ensucian la convención.

var real = EntityCatalog.All.Where(ReportableTables.IsDefault).ToList();

// Override de dueño de clave donde el heurístico falla (la maestra NO es la de más columnas; ej. CI/AdPreJub).
var keyOwnerOverride = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
{
    ["CI"] = "Afiliado",
};

// nombre de columna clave -> entidad real de clave simple dueña (desempate: override, si no la de más columnas).
var realByKey = real.Where(m => m.Keys.Count == 1)
    .GroupBy(m => m.Keys[0].Name, StringComparer.OrdinalIgnoreCase)
    .ToDictionary(
        g => g.Key,
        g => keyOwnerOverride.TryGetValue(g.Key, out var owner)
                ? g.FirstOrDefault(m => m.Table.Equals(owner, StringComparison.OrdinalIgnoreCase))
                    ?? g.OrderByDescending(m => m.Columns.Count).First()
                : g.OrderByDescending(m => m.Columns.Count).First(),
        StringComparer.OrdinalIgnoreCase);

var nav = new StringBuilder();
nav.AppendLine("// <auto-generated> Propiedades de navegación para reportes (ObjectDataSource).");
nav.AppendLine("// Generado por tools/Sgpa.NavGen. NO editar a mano. </auto-generated>");
nav.AppendLine("#nullable enable");
nav.AppendLine("using System.Collections.Generic;");
nav.AppendLine();
nav.AppendLine("namespace Sgpa.Domain.Entities;");
nav.AppendLine();

var map = new StringBuilder();
map.AppendLine("// <auto-generated> Mapa de relaciones para el loader de reportes. Generado por tools/Sgpa.NavGen. </auto-generated>");
map.AppendLine("#nullable enable");
map.AppendLine("using System;");
map.AppendLine("using System.Collections.Generic;");
map.AppendLine("using Sgpa.Domain.Entities;");
map.AppendLine();
map.AppendLine("namespace Sgpa.Domain.Metadata;");
map.AppendLine();
map.AppendLine("public enum ReportNavKind { Reference, Collection }");
map.AppendLine();
map.AppendLine("/// <summary>Relación de navegación: prop a poblar, tipo remoto y columna de join (mismo nombre a ambos lados).</summary>");
map.AppendLine("public sealed record ReportNavLink(string PropName, ReportNavKind Kind, Type Remote, string JoinColumn);");
map.AppendLine();
map.AppendLine("public static class ReportNavMap");
map.AppendLine("{");
map.AppendLine("    public static readonly IReadOnlyDictionary<Type, IReadOnlyList<ReportNavLink>> Map =");
map.AppendLine("        new Dictionary<Type, IReadOnlyList<ReportNavLink>>");
map.AppendLine("        {");

int conNav = 0, totalRefs = 0, totalCols = 0;

foreach (var e in real.OrderBy(m => m.EntityType.Name, StringComparer.Ordinal))
{
    var used = new HashSet<string>(e.Columns.Select(c => c.Property.Name), StringComparer.OrdinalIgnoreCase)
    {
        e.EntityType.Name,
    };

    // N-a-1: columnas de E que apuntan a otra entidad real. JoinColumn = nombre de PROPIEDAD C# (para reflexión
    // en el loader; el nombre de columna DB se resuelve después vía metadata). Por convención coincide a ambos lados.
    var refs = new List<(string Type, string Name, string Join)>();
    foreach (var col in e.Columns)
    {
        var parent = ParentRef(col, e);
        if (parent is null) continue;
        refs.Add((parent.EntityType.Name, UniqueRef(RefName(col.Property.Name, parent.EntityType.Name), used), col.Property.Name));
    }

    // 1-a-N: entidades reales con una columna apuntando a E. JoinColumn = nombre de PROPIEDAD C# de esa FK.
    var cols = new List<(string Type, string Name, string Join)>();
    foreach (var child in real)
    {
        if (child.EntityType == e.EntityType) continue;
        var fk = child.Columns.FirstOrDefault(c => Points(c, child, e));
        if (fk is null) continue;
        cols.Add((child.EntityType.Name, Unique(Plural(child.EntityType.Name), used), fk.Property.Name));
    }

    if (refs.Count == 0 && cols.Count == 0) continue;
    conNav++; totalRefs += refs.Count; totalCols += cols.Count;

    nav.AppendLine($"public partial class {e.EntityType.Name}");
    nav.AppendLine("{");
    foreach (var (type, name, _) in refs)
        nav.AppendLine($"    public {type}? {name} {{ get; set; }} // referencia N-a-1");
    foreach (var (type, name, _) in cols)
        nav.AppendLine($"    public List<{type}> {name} {{ get; set; }} = new(); // colección 1-a-N");
    nav.AppendLine("}");
    nav.AppendLine();

    map.AppendLine($"            [typeof({e.EntityType.Name})] = new ReportNavLink[]");
    map.AppendLine("            {");
    foreach (var (type, name, join) in refs)
        map.AppendLine($"                new(\"{name}\", ReportNavKind.Reference, typeof({type}), \"{join}\"),");
    foreach (var (type, name, join) in cols)
        map.AppendLine($"                new(\"{name}\", ReportNavKind.Collection, typeof({type}), \"{join}\"),");
    map.AppendLine("            },");
}

map.AppendLine("        };");
map.AppendLine("}");

var navPath = args.Length > 0
    ? args[0]
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..",
        "src", "Sgpa.Domain", "Entities", "Generated", "EntityNavigation.g.cs"));
var mapPath = Path.Combine(Path.GetDirectoryName(navPath)!, "ReportNavMap.g.cs");

File.WriteAllText(navPath, nav.ToString());
File.WriteAllText(mapPath, map.ToString());
Console.WriteLine($"Generado: {navPath}");
Console.WriteLine($"Generado: {mapPath}");
Console.WriteLine($"Reales: {real.Count} / {EntityCatalog.All.Count}.  Con navegación: {conNav}  (refs: {totalRefs}, colecciones: {totalCols})");

// Padre de una columna FK de 'owner' (excluye la propia identidad simple de owner para no auto-referenciar).
EntityMetadata? ParentRef(ColumnMetadata col, EntityMetadata owner)
{
    if (col.IsAudit) return null;
    if (owner.Keys.Count == 1 && string.Equals(owner.Key.Name, col.Name, StringComparison.OrdinalIgnoreCase))
        return null;
    return realByKey.TryGetValue(col.Name, out var p) && p.EntityType != owner.EntityType ? p : null;
}

// ¿La columna 'col' de 'child' apunta a la entidad 'target'?
bool Points(ColumnMetadata col, EntityMetadata child, EntityMetadata target)
{
    if (col.IsAudit) return false;
    return realByKey.TryGetValue(col.Name, out var p)
        && p.EntityType == target.EntityType
        && p.EntityType != child.EntityType;
}

static string RefName(string fkProp, string parentName)
    => fkProp.StartsWith("Cod", StringComparison.Ordinal) && fkProp.Length > 3
        ? fkProp[3..]
        : parentName;

static string Plural(string n)
    => n.EndsWith("s", StringComparison.OrdinalIgnoreCase) ? n : n + "s";

static string Unique(string name, HashSet<string> used)
{
    var n = name;
    var i = 1;
    while (!used.Add(n)) n = name + ++i;
    return n;
}

// Para referencias: si la FK se llama igual que la entidad (ej. columna "Mutualista"), preferimos sufijo "Ref".
static string UniqueRef(string name, HashSet<string> used)
{
    if (used.Add(name)) return name;
    if (used.Add(name + "Ref")) return name + "Ref";
    return Unique(name + "Ref", used);
}
