[General]
Version=1.0
Release=1
Sistema=S.P.
Empresa=Casemed
;Entorno=1

[Connect]
PathRpt=L-Rpt.mdb
;PathSGPA=X-\\SERVIDORXP\SERVIDOR_C\Gestion\SGPA\Data\SgpaServ.mdb
;PathSeguServ=X-\\SERVIDORXP\SERVIDOR_C\Gestion\SGPA\Data\Seguserv.mdb
;PathSGPA=X-f:\soft\Gestion\sgpa\Data\SgpaServ.mdb
;PathSeguServ=X-c:\opc6\extras\programas\Gestion\SGPA\Data\Seguserv.mdb
;PathSGPA=X-c:\opc6\extras\programas\Gestion\sgpa\Data\SgpaServ.mdb
PathSeguServ=x-c:\personal\Gestion\SGPA\Data\Seguserv.mdb
PathSGPA=x-c:\personal\Gestion\SGPA\Data\Sgpaserv.mdb
Grupo_Usuario=PathSeguserv
Afiliado=PathSGPA
Empresa=PathSGPA
Trabaja=PathSGPA
SubsidioCabezal=PathSGPA
rptCheque_Tmp=PathRpt
rptPlanes_Tmp=PathRpt
rptVale_Tmp=PathRpt
rptTIR_Tmp=PathRpt

[Liquidos]
MesHL=02
AñoHL=2011
FileHL=C:\Documents and Settings\Administrador\Escritorio\Libro1.xls
EmpresaHL=8
[Pagos]
Archivo=C:\Documents and Settings\Administrador\Escritorio
