[General]
Nom_MDB=SP.MDB
Nom_MDB_Servidor=SPServ.Mdb
Nom_MDB_Seguridad=Segurida.MDB
Nom_MDB_Seguridad_Servidor=SeguServ.Mdb
;Nom_Dir_Servidor=\\servidorxp\servidor_c\Gestion\SP\DATA
;Nom_Dir_Version=\\servidorxp\servidor_c\Gestion\SP\VERSION
;Nom_Dir_Servidor=c:\opc6\extras\programas\Gestion\SP\DATA
;Nom_Dir_Version=c:\opc6\extras\programas\Gestion\SP\VERSION
Nom_Dir_Servidor=c:\personal\Gestion\SP\DATA
Nom_Dir_Version=c:\personal\Gestion\SP\VERSION
Automatico=True
Release=1

[Exes]
Programa=SP.EXE
Seguridad=Segurida.exe