//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'AdPreJub'.</summary>
	public partial class AdPreJub : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="AdPreJub"/> class.</summary>
		public AdPreJub() : base()
		{
			this.AdPreJubPagos = new List<AdPreJubPago>();
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the FechaJubilacion field. </summary>
		public Nullable<System.DateTime> FechaJubilacion { get; set; }
		/// <summary>Gets or sets the FechaPresentacion field. </summary>
		public Nullable<System.DateTime> FechaPresentacion { get; set; }
		/// <summary>Gets or sets the ImporteMensual field. </summary>
		public Nullable<System.Int16> ImporteMensual { get; set; }
		/// <summary>Gets or sets the Observaciones field. </summary>
		public System.String? Observaciones { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AdPreJubPago.AdPreJub - AdPreJub.AdPreJubPagos (m:1)'</summary>
		public virtual List<AdPreJubPago> AdPreJubPagos { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AdPreJub.Afiliado - Afiliado.AdPreJub (1:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
	}
}
