//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'AfeccionTipo'.</summary>
	public partial class AfeccionTipo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="AfeccionTipo"/> class.</summary>
		public AfeccionTipo() : base()
		{
			this.Certificacions = new List<Certificacion>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodAfeccionGrupo field. </summary>
		public Nullable<System.Int32> CodAfeccionGrupo { get; set; }
		/// <summary>Gets or sets the CodAfeccionTipo field. </summary>
		public System.Int16 CodAfeccionTipo { get; set; }
		/// <summary>Gets or sets the CodDiameg field. </summary>
		public Nullable<System.Int32> CodDiameg { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AfeccionTipo.AfeccionGrupo - AfeccionGrupo.AfeccionTipos (m:1)'</summary>
		public virtual AfeccionGrupo? AfeccionGrupo { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.AfeccionTipo - AfeccionTipo.Certificacions (m:1)'</summary>
		public virtual List<Certificacion> Certificacions { get; set; }
	}
}
