//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Afiliado'.</summary>
	public partial class Afiliado : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Afiliado"/> class.</summary>
		public Afiliado() : base()
		{
			this.AfiliadoApuntes = new List<AfiliadoApunte>();
			this.AfiliadoEspecialidads = new List<AfiliadoEspecialidad>();
			this.Certificacions = new List<Certificacion>();
			this.CertificacionProrrogas = new List<CertificacionProrroga>();
			this.Prestacions = new List<Prestacion>();
			this.ReintegroMutuals = new List<ReintegroMutual>();
			this.SubsidioCabezals = new List<SubsidioCabezal>();
			this.Trabajas = new List<Trabaja>();
			OnCreated();
		}

		/// <summary>Gets or sets the Apellido1 field. </summary>
		public System.String? Apellido1 { get; set; }
		/// <summary>Gets or sets the Apellido2 field. </summary>
		public System.String? Apellido2 { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodBanco field. </summary>
		public Nullable<System.Int32> CodBanco { get; set; }
		/// <summary>Gets or sets the CodDepartamento field. </summary>
		public System.String? CodDepartamento { get; set; }
		/// <summary>Gets or sets the CodMutualista field. </summary>
		public Nullable<System.Int16> CodMutualista { get; set; }
		/// <summary>Gets or sets the CodRegimenJubilatorio field. </summary>
		public Nullable<System.Byte> CodRegimenJubilatorio { get; set; }
		/// <summary>Gets or sets the CodSituacionMutual field. </summary>
		public System.String? CodSituacionMutual { get; set; }
		/// <summary>Gets or sets the Direccion field. </summary>
		public System.String? Direccion { get; set; }
		/// <summary>Gets or sets the Email field. </summary>
		public System.String? Email { get; set; }
		/// <summary>Gets or sets the FechaBajaMutualista field. </summary>
		public Nullable<System.DateTime> FechaBajaMutualista { get; set; }
		/// <summary>Gets or sets the FechaIngMutualista field. </summary>
		public Nullable<System.DateTime> FechaIngMutualista { get; set; }
		/// <summary>Gets or sets the FechaNacimiento field. </summary>
		public Nullable<System.DateTime> FechaNacimiento { get; set; }
		/// <summary>Gets or sets the Movil field. </summary>
		public System.String? Movil { get; set; }
		/// <summary>Gets or sets the Nombres field. </summary>
		public System.String? Nombres { get; set; }
		/// <summary>Gets or sets the NroCuenta field. </summary>
		public System.String? NroCuenta { get; set; }
		/// <summary>Gets or sets the NroFunCuenta field. </summary>
		public System.String? NroFunCuenta { get; set; }
		/// <summary>Gets or sets the NroSocioMutualista field. </summary>
		public System.String? NroSocioMutualista { get; set; }
		/// <summary>Gets or sets the PagaMutualista field. </summary>
		public Nullable<System.Boolean> PagaMutualista { get; set; }
		/// <summary>Gets or sets the Sexo field. </summary>
		public System.String? Sexo { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Telefono field. </summary>
		public System.String? Telefono { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AdPreJub.Afiliado - Afiliado.AdPreJub (1:1)'</summary>
		public virtual AdPreJub? AdPreJub { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AfiliadoApunte.Afiliado - Afiliado.AfiliadoApuntes (m:1)'</summary>
		public virtual List<AfiliadoApunte> AfiliadoApuntes { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AfiliadoEspecialidad.Afiliado - Afiliado.AfiliadoEspecialidads (m:1)'</summary>
		public virtual List<AfiliadoEspecialidad> AfiliadoEspecialidads { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.Banco - Banco.Afiliados (m:1)'</summary>
		public virtual Banco? Banco { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.Afiliado - Afiliado.Certificacions (m:1)'</summary>
		public virtual List<Certificacion> Certificacions { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'CertificacionProrroga.Afiliado - Afiliado.CertificacionProrrogas (m:1)'</summary>
		public virtual List<CertificacionProrroga> CertificacionProrrogas { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.Mutualistum - Mutualistum.Afiliados (m:1)'</summary>
		public virtual Mutualistum? Mutualistum { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.Afiliado - Afiliado.Prestacions (m:1)'</summary>
		public virtual List<Prestacion> Prestacions { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'PrimaFallecimiento.Afiliado - Afiliado.PrimaFallecimiento (1:1)'</summary>
		public virtual PrimaFallecimiento? PrimaFallecimiento { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.RegimenJubilatorio - RegimenJubilatorio.Afiliados (m:1)'</summary>
		public virtual RegimenJubilatorio? RegimenJubilatorio { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'ReintegroMutual.Afiliado - Afiliado.ReintegroMutuals (m:1)'</summary>
		public virtual List<ReintegroMutual> ReintegroMutuals { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezal.Afiliado - Afiliado.SubsidioCabezals (m:1)'</summary>
		public virtual List<SubsidioCabezal> SubsidioCabezals { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.Afiliado - Afiliado.Trabajas (m:1)'</summary>
		public virtual List<Trabaja> Trabajas { get; set; }
	}
}
