//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'AfiliadoEspecialidad'.</summary>
	public partial class AfiliadoEspecialidad : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _afiliadoEspecialidadId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="AfiliadoEspecialidad"/> class.</summary>
		public AfiliadoEspecialidad() : base()
		{
			OnCreated();
		}

		/// <summary>Gets the AfiliadoEspecialidadId field. </summary>
		public System.Int32 AfiliadoEspecialidadId => _afiliadoEspecialidadId;
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodEspecialidad field. </summary>
		public System.Int32 CodEspecialidad { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AfiliadoEspecialidad.Afiliado - Afiliado.AfiliadoEspecialidads (m:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'AfiliadoEspecialidad.Especialidad - Especialidad.AfiliadoEspecialidads (m:1)'</summary>
		public virtual Especialidad Especialidad { get; set; } = null!;
	}
}
