//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'BajaMotivo'.</summary>
	public partial class BajaMotivo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="BajaMotivo"/> class.</summary>
		public BajaMotivo() : base()
		{
			this.Trabajas = new List<Trabaja>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodBajaMotivo field. </summary>
		public System.Int32 CodBajaMotivo { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.BajaMotivo - BajaMotivo.Trabajas (m:1)'</summary>
		public virtual List<Trabaja> Trabajas { get; set; }
	}
}
