//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Banco'.</summary>
	public partial class Banco : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Banco"/> class.</summary>
		public Banco() : base()
		{
			this.Afiliados = new List<Afiliado>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodBanco field. </summary>
		public System.Int32 CodBanco { get; set; }
		/// <summary>Gets or sets the Descripcion field. </summary>
		public System.String? Descripcion { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.Banco - Banco.Afiliados (m:1)'</summary>
		public virtual List<Afiliado> Afiliados { get; set; }
	}
}
