//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Certificador'.</summary>
	public partial class Certificador : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Certificador"/> class.</summary>
		public Certificador() : base()
		{
			this.Certificacions = new List<Certificacion>();
			OnCreated();
		}

		/// <summary>Gets or sets the Bip field. </summary>
		public System.String? Bip { get; set; }
		/// <summary>Gets or sets the CobraLlamado field. </summary>
		public Nullable<System.Boolean> CobraLlamado { get; set; }
		/// <summary>Gets or sets the CodCertificador field. </summary>
		public System.Int16 CodCertificador { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Direccion field. </summary>
		public System.String? Direccion { get; set; }
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String? Fax { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Telefono field. </summary>
		public System.String? Telefono { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.Certificador - Certificador.Certificacions (m:1)'</summary>
		public virtual List<Certificacion> Certificacions { get; set; }
	}
}
