//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'CertificacionProrroga'.</summary>
	public partial class CertificacionProrroga : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _certificacionProrrogaId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="CertificacionProrroga"/> class.</summary>
		public CertificacionProrroga() : base()
		{
			OnCreated();
		}

		/// <summary>Gets the CertificacionProrrogaId field. </summary>
		public System.Int32 CertificacionProrrogaId => _certificacionProrrogaId;
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the Dias field. </summary>
		public Nullable<System.Int32> Dias { get; set; }
		/// <summary>Gets or sets the Fecha field. </summary>
		public System.DateTime Fecha { get; set; }
		/// <summary>Gets or sets the Observaciones field. </summary>
		public System.String? Observaciones { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'CertificacionProrroga.Afiliado - Afiliado.CertificacionProrrogas (m:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
	}
}
