//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Certificacion'.</summary>
	public partial class Certificacion : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Certificacion"/> class.</summary>
		public Certificacion() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public Nullable<System.Int32> Ci { get; set; }
		/// <summary>Gets or sets the CodAfeccionTipo field. </summary>
		public Nullable<System.Int16> CodAfeccionTipo { get; set; }
		/// <summary>Gets or sets the CodCertificador field. </summary>
		public Nullable<System.Int16> CodCertificador { get; set; }
		/// <summary>Gets or sets the CodSalidaTipo field. </summary>
		public Nullable<System.Int16> CodSalidaTipo { get; set; }
		/// <summary>Gets or sets the Efectiva field. </summary>
		public Nullable<System.Boolean> Efectiva { get; set; }
		/// <summary>Gets or sets the FechaCertificacion field. </summary>
		public Nullable<System.DateTime> FechaCertificacion { get; set; }
		/// <summary>Gets or sets the FechaFin field. </summary>
		public Nullable<System.DateTime> FechaFin { get; set; }
		/// <summary>Gets or sets the FechaIni field. </summary>
		public Nullable<System.DateTime> FechaIni { get; set; }
		/// <summary>Gets or sets the FechaRecibido field. </summary>
		public Nullable<System.DateTime> FechaRecibido { get; set; }
		/// <summary>Gets or sets the ImporteDeducible field. </summary>
		public Nullable<System.Double> ImporteDeducible { get; set; }
		/// <summary>Gets or sets the Indicaciones field. </summary>
		public System.String? Indicaciones { get; set; }
		/// <summary>Gets or sets the NroLlamado field. </summary>
		public System.Int32 NroLlamado { get; set; }
		/// <summary>Gets or sets the NroRecibo field. </summary>
		public Nullable<System.Int32> NroRecibo { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Trabaja field. </summary>
		public Nullable<System.Boolean> Trabaja { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.AfeccionTipo - AfeccionTipo.Certificacions (m:1)'</summary>
		public virtual AfeccionTipo? AfeccionTipo { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.Afiliado - Afiliado.Certificacions (m:1)'</summary>
		public virtual Afiliado? Afiliado { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.Certificador - Certificador.Certificacions (m:1)'</summary>
		public virtual Certificador? Certificador { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.SalidaTipo - SalidaTipo.Certificacions (m:1)'</summary>
		public virtual SalidaTipo? SalidaTipo { get; set; }
	}
}
