//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Cuentum'.</summary>
	public partial class Cuentum : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Cuentum"/> class.</summary>
		public Cuentum() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public Nullable<System.Int32> Ci { get; set; }
		/// <summary>Gets or sets the CodBanco field. </summary>
		public Nullable<System.Int32> CodBanco { get; set; }
		/// <summary>Gets or sets the NroCuenta field. </summary>
		public System.String? NroCuenta { get; set; }
	}
}
