//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Departamento'.</summary>
	public partial class Departamento : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Departamento"/> class.</summary>
		public Departamento() : base()
		{
			this.CodDepartamento = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the CodDepartamento field. </summary>
		public System.String CodDepartamento { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
	}
}
