//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Discount'.</summary>
	public partial class Discount : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Discount"/> class.</summary>
		public Discount() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public Nullable<System.Double> Ci { get; set; }
		/// <summary>Gets or sets the Ficha field. </summary>
		public Nullable<System.Double> Ficha { get; set; }
		/// <summary>Gets or sets the NºCuenta field. </summary>
		public Nullable<System.Double> NºCuenta { get; set; }
		/// <summary>Gets or sets the NombreYApellido field. </summary>
		public System.String? NombreYApellido { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
	}
}
