//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'EmpresaPago'.</summary>
	public partial class EmpresaPago : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _empresaPagoId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="EmpresaPago"/> class.</summary>
		public EmpresaPago() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public System.Int32 Anio { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets the EmpresaPagoId field. </summary>
		public System.Int32 EmpresaPagoId => _empresaPagoId;
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Int32> Importe { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public System.Int16 Mes { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'EmpresaPago.Empresa - Empresa.EmpresaPagos (m:1)'</summary>
		public virtual Empresa Empresa { get; set; } = null!;
	}
}
