//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Empresa'.</summary>
	public partial class Empresa : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Empresa"/> class.</summary>
		public Empresa() : base()
		{
			this.EmpresaPagos = new List<EmpresaPago>();
			this.SubsidioCabezalEmpresas = new List<SubsidioCabezalEmpresa>();
			this.SubsidioImponibles = new List<SubsidioImponible>();
			this.SubsidioItemEmpresas = new List<SubsidioItemEmpresa>();
			this.Trabajas = new List<Trabaja>();
			OnCreated();
		}

		/// <summary>Gets or sets the AporteAguinaldo field. </summary>
		public Nullable<System.Int32> AporteAguinaldo { get; set; }
		/// <summary>Gets or sets the AporteCasemed field. </summary>
		public Nullable<System.Single> AporteCasemed { get; set; }
		/// <summary>Gets or sets the Autoridades field. </summary>
		public System.String? Autoridades { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets or sets the CodRegimenAporte field. </summary>
		public Nullable<System.Int16> CodRegimenAporte { get; set; }
		/// <summary>Gets or sets the CodSituacionPago field. </summary>
		public Nullable<System.Int16> CodSituacionPago { get; set; }
		/// <summary>Gets or sets the Direccion field. </summary>
		public System.String? Direccion { get; set; }
		/// <summary>Gets or sets the Email field. </summary>
		public System.String? Email { get; set; }
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String? Fax { get; set; }
		/// <summary>Gets or sets the Ficticia field. </summary>
		public Nullable<System.Boolean> Ficticia { get; set; }
		/// <summary>Gets or sets the Liquidar field. </summary>
		public Nullable<System.Boolean> Liquidar { get; set; }
		/// <summary>Gets or sets the Nombre field. </summary>
		public System.String? Nombre { get; set; }
		/// <summary>Gets or sets the PersonaContacto field. </summary>
		public System.String? PersonaContacto { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Telefono field. </summary>
		public System.String? Telefono { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'EmpresaPago.Empresa - Empresa.EmpresaPagos (m:1)'</summary>
		public virtual List<EmpresaPago> EmpresaPagos { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Empresa.RegimenAporte - RegimenAporte.Empresas (m:1)'</summary>
		public virtual RegimenAporte? RegimenAporte { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Empresa.SituacionPago - SituacionPago.Empresas (m:1)'</summary>
		public virtual SituacionPago? SituacionPago { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalEmpresa.Empresa - Empresa.SubsidioCabezalEmpresas (m:1)'</summary>
		public virtual List<SubsidioCabezalEmpresa> SubsidioCabezalEmpresas { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioImponible.Empresa - Empresa.SubsidioImponibles (m:1)'</summary>
		public virtual List<SubsidioImponible> SubsidioImponibles { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItemEmpresa.Empresa - Empresa.SubsidioItemEmpresas (m:1)'</summary>
		public virtual List<SubsidioItemEmpresa> SubsidioItemEmpresas { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.Empresa - Empresa.Trabajas (m:1)'</summary>
		public virtual List<Trabaja> Trabajas { get; set; }
	}
}
