//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Especialidad'.</summary>
	public partial class Especialidad : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Especialidad"/> class.</summary>
		public Especialidad() : base()
		{
			this.AfiliadoEspecialidads = new List<AfiliadoEspecialidad>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodEspecialidad field. </summary>
		public System.Int32 CodEspecialidad { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'AfiliadoEspecialidad.Especialidad - Especialidad.AfiliadoEspecialidads (m:1)'</summary>
		public virtual List<AfiliadoEspecialidad> AfiliadoEspecialidads { get; set; }
	}
}
