//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'FormaPago'.</summary>
	public partial class FormaPago : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="FormaPago"/> class.</summary>
		public FormaPago() : base()
		{
			this.Mutualista = new List<Mutualistum>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodFormaPago field. </summary>
		public System.Int16 CodFormaPago { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Mutualistum.FormaPago - FormaPago.Mutualista (m:1)'</summary>
		public virtual List<Mutualistum> Mutualista { get; set; }
	}
}
