//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'FranjaIrpf'.</summary>
	public partial class FranjaIrpf : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="FranjaIrpf"/> class.</summary>
		public FranjaIrpf() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Desde field. </summary>
		public System.Double Desde { get; set; }
		/// <summary>Gets or sets the Hasta field. </summary>
		public Nullable<System.Double> Hasta { get; set; }
		/// <summary>Gets or sets the Porcentaje field. </summary>
		public Nullable<System.Double> Porcentaje { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
	}
}
