//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Imponible'.</summary>
	public partial class Imponible : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _imponibleId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Imponible"/> class.</summary>
		public Imponible() : base()
		{
			this.Concepto = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public System.Int16 Anio { get; set; }
		/// <summary>Gets or sets the AnioMes field. </summary>
		public Nullable<System.Int32> AnioMes { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets or sets the Concepto field. </summary>
		public System.String Concepto { get; set; }
		/// <summary>Gets or sets the DiasTrabajados field. </summary>
		public Nullable<System.Int16> DiasTrabajados { get; set; }
		/// <summary>Gets or sets the Fechaingreso field. </summary>
		public System.DateTime Fechaingreso { get; set; }
		/// <summary>Gets or sets the IdTrabaja field. </summary>
		public Nullable<System.Int32> IdTrabaja { get; set; }
		/// <summary>Gets the ImponibleId field. </summary>
		public System.Int32 ImponibleId => _imponibleId;
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public System.Byte Mes { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Imponible.Trabaja - Trabaja.Imponibles (m:1)'</summary>
		public virtual Trabaja? Trabaja { get; set; }
	}
}
