//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'InformeEstadistico'.</summary>
	public partial class InformeEstadistico : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="InformeEstadistico"/> class.</summary>
		public InformeEstadistico() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Comentario field. </summary>
		public System.String? Comentario { get; set; }
		/// <summary>Gets or sets the Empresa field. </summary>
		public Nullable<System.Boolean> Empresa { get; set; }
		/// <summary>Gets or sets the Fecha field. </summary>
		public Nullable<System.Boolean> Fecha { get; set; }
		/// <summary>Gets or sets the Grupo field. </summary>
		public System.String? Grupo { get; set; }
		/// <summary>Gets or sets the GrupoEtario field. </summary>
		public Nullable<System.Boolean> GrupoEtario { get; set; }
		/// <summary>Gets or sets the IdRpt field. </summary>
		public System.Int32 IdRpt { get; set; }
		/// <summary>Gets or sets the MesAnio field. </summary>
		public Nullable<System.Boolean> MesAnio { get; set; }
		/// <summary>Gets or sets the Orden field. </summary>
		public Nullable<System.Int32> Orden { get; set; }
		/// <summary>Gets or sets the Patologia field. </summary>
		public Nullable<System.Boolean> Patologia { get; set; }
		/// <summary>Gets or sets the Periodo field. </summary>
		public Nullable<System.Boolean> Periodo { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the TituloPantalla field. </summary>
		public System.String? TituloPantalla { get; set; }
		/// <summary>Gets or sets the TituloRpt field. </summary>
		public System.String? TituloRpt { get; set; }
	}
}
