//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'LiquidacionBp'.</summary>
	public partial class LiquidacionBp : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _liquidacionBpsid = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="LiquidacionBp"/> class.</summary>
		public LiquidacionBp() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public Nullable<System.Int16> Anio { get; set; }
		/// <summary>Gets or sets the Apellido field. </summary>
		public System.String? Apellido { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Double Ci { get; set; }
		/// <summary>Gets or sets the FechaDeEntrega field. </summary>
		public Nullable<System.DateTime> FechaDeEntrega { get; set; }
		/// <summary>Gets or sets the FechaPerDesde field. </summary>
		public Nullable<System.DateTime> FechaPerDesde { get; set; }
		/// <summary>Gets or sets the FechaPerHasta field. </summary>
		public Nullable<System.DateTime> FechaPerHasta { get; set; }
		/// <summary>Gets the LiquidacionBpsid field. </summary>
		public System.Int32 LiquidacionBpsid => _liquidacionBpsid;
		/// <summary>Gets or sets the Liquido field. </summary>
		public Nullable<System.Double> Liquido { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public Nullable<System.Int16> Mes { get; set; }
		/// <summary>Gets or sets the MesDeCargo field. </summary>
		public System.Int32 MesDeCargo { get; set; }
		/// <summary>Gets or sets the MontoTotal field. </summary>
		public Nullable<System.Double> MontoTotal { get; set; }
		/// <summary>Gets or sets the NEntrega field. </summary>
		public Nullable<System.Int32> NEntrega { get; set; }
		/// <summary>Gets or sets the Nombre field. </summary>
		public System.String? Nombre { get; set; }
		/// <summary>Gets or sets the NomEmpresa field. </summary>
		public System.String? NomEmpresa { get; set; }
		/// <summary>Gets or sets the PctPorEmpresa field. </summary>
		public System.Double PctPorEmpresa { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
	}
}
