//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'MaeFun'.</summary>
	public partial class MaeFun : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="MaeFun"/> class.</summary>
		public MaeFun() : base()
		{
			this.Apellido1 = string.Empty;
			this.Nombre1 = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the Apellido1 field. </summary>
		public System.String Apellido1 { get; set; }
		/// <summary>Gets or sets the Apellido2 field. </summary>
		public System.String? Apellido2 { get; set; }
		/// <summary>Gets or sets the AsigCuenta field. </summary>
		public Nullable<System.Int16> AsigCuenta { get; set; }
		/// <summary>Gets or sets the Cedula field. </summary>
		public Nullable<System.Int32> Cedula { get; set; }
		/// <summary>Gets or sets the CodCargo field. </summary>
		public Nullable<System.Int32> CodCargo { get; set; }
		/// <summary>Gets or sets the DesCargo field. </summary>
		public System.String? DesCargo { get; set; }
		/// <summary>Gets or sets the DirApto field. </summary>
		public System.String? DirApto { get; set; }
		/// <summary>Gets or sets the DirBis field. </summary>
		public System.String? DirBis { get; set; }
		/// <summary>Gets or sets the DirBloque field. </summary>
		public System.String? DirBloque { get; set; }
		/// <summary>Gets or sets the DirCalle field. </summary>
		public System.String? DirCalle { get; set; }
		/// <summary>Gets or sets the DirLocal field. </summary>
		public System.String? DirLocal { get; set; }
		/// <summary>Gets or sets the DirPiso field. </summary>
		public System.String? DirPiso { get; set; }
		/// <summary>Gets or sets the DirPuerta field. </summary>
		public System.String? DirPuerta { get; set; }
		/// <summary>Gets or sets the EstCivil field. </summary>
		public Nullable<System.Int16> EstCivil { get; set; }
		/// <summary>Gets or sets the FecAsigCta field. </summary>
		public Nullable<System.DateTime> FecAsigCta { get; set; }
		/// <summary>Gets or sets the FecInfDbla field. </summary>
		public Nullable<System.DateTime> FecInfDbla { get; set; }
		/// <summary>Gets or sets the FecIngreso field. </summary>
		public Nullable<System.DateTime> FecIngreso { get; set; }
		/// <summary>Gets or sets the FecNac field. </summary>
		public Nullable<System.DateTime> FecNac { get; set; }
		/// <summary>Gets or sets the InfDbla field. </summary>
		public Nullable<System.Boolean> InfDbla { get; set; }
		/// <summary>Gets or sets the Nacionalidad field. </summary>
		public Nullable<System.Int16> Nacionalidad { get; set; }
		/// <summary>Gets or sets the Nombre1 field. </summary>
		public System.String Nombre1 { get; set; }
		/// <summary>Gets or sets the Nombre2 field. </summary>
		public System.String? Nombre2 { get; set; }
		/// <summary>Gets or sets the NroCuenta field. </summary>
		public Nullable<System.Int32> NroCuenta { get; set; }
		/// <summary>Gets or sets the NroFun field. </summary>
		public System.Int32 NroFun { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Telefono field. </summary>
		public System.String? Telefono { get; set; }
	}
}
