//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Moneda'.</summary>
	public partial class Moneda : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Moneda"/> class.</summary>
		public Moneda() : base()
		{
			this.Prestacions = new List<Prestacion>();
			this.Simbolo = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the Simbolo field. </summary>
		public System.String Simbolo { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.Moneda1 - Moneda.Prestacions (m:1)'</summary>
		public virtual List<Prestacion> Prestacions { get; set; }
	}
}
