//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Mutualistum'.</summary>
	public partial class Mutualistum : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Mutualistum"/> class.</summary>
		public Mutualistum() : base()
		{
			this.Afiliados = new List<Afiliado>();
			this.ReintegroMutuals = new List<ReintegroMutual>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodFormaPago field. </summary>
		public Nullable<System.Int16> CodFormaPago { get; set; }
		/// <summary>Gets or sets the CodMutualista field. </summary>
		public System.Int16 CodMutualista { get; set; }
		/// <summary>Gets or sets the Cuota field. </summary>
		public Nullable<System.Double> Cuota { get; set; }
		/// <summary>Gets or sets the DiaPago field. </summary>
		public Nullable<System.Byte> DiaPago { get; set; }
		/// <summary>Gets or sets the Direccion field. </summary>
		public System.String? Direccion { get; set; }
		/// <summary>Gets or sets the Email field. </summary>
		public System.String? Email { get; set; }
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String? Fax { get; set; }
		/// <summary>Gets or sets the Ficticia field. </summary>
		public Nullable<System.Boolean> Ficticia { get; set; }
		/// <summary>Gets or sets the Nombre field. </summary>
		public System.String? Nombre { get; set; }
		/// <summary>Gets or sets the PersonaContacto field. </summary>
		public System.String? PersonaContacto { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Telefono field. </summary>
		public System.String? Telefono { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.Mutualistum - Mutualistum.Afiliados (m:1)'</summary>
		public virtual List<Afiliado> Afiliados { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Mutualistum.FormaPago - FormaPago.Mutualista (m:1)'</summary>
		public virtual FormaPago? FormaPago { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'ReintegroMutual.Mutualistum - Mutualistum.ReintegroMutuals (m:1)'</summary>
		public virtual List<ReintegroMutual> ReintegroMutuals { get; set; }
	}
}
