//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'NoCargadoHl'.</summary>
	public partial class NoCargadoHl : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _noCargadoHlid = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="NoCargadoHl"/> class.</summary>
		public NoCargadoHl() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public System.Int32 Anio { get; set; }
		/// <summary>Gets or sets the Apellido1 field. </summary>
		public System.String? Apellido1 { get; set; }
		/// <summary>Gets or sets the Apellido2 field. </summary>
		public System.String? Apellido2 { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int32 CodEmpresa { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public System.Int32 Mes { get; set; }
		/// <summary>Gets the NoCargadoHlid field. </summary>
		public System.Int32 NoCargadoHlid => _noCargadoHlid;
		/// <summary>Gets or sets the Nombres field. </summary>
		public System.String? Nombres { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
	}
}
