//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Parametro'.</summary>
	public partial class Parametro : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Parametro"/> class.</summary>
		public Parametro() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Bcp field. </summary>
		public Nullable<System.Double> Bcp { get; set; }
		/// <summary>Gets or sets the PctAdPreJub field. </summary>
		public Nullable<System.Single> PctAdPreJub { get; set; }
		/// <summary>Gets or sets the PctBps field. </summary>
		public Nullable<System.Double> PctBps { get; set; }
		/// <summary>Gets or sets the Smn field. </summary>
		public Nullable<System.Double> Smn { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the TopeJubilatorio field. </summary>
		public Nullable<System.Single> TopeJubilatorio { get; set; }
		/// <summary>Gets or sets the TopeLiquidoBps field. </summary>
		public Nullable<System.Double> TopeLiquidoBps { get; set; }
		/// <summary>Gets or sets the TopePrima field. </summary>
		public Nullable<System.Single> TopePrima { get; set; }
		/// <summary>Gets or sets the Ur field. </summary>
		public Nullable<System.Single> Ur { get; set; }
	}
}
