//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Prestacion'.</summary>
	public partial class Prestacion : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _prestacionId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Prestacion"/> class.</summary>
		public Prestacion() : base()
		{
			this.Receta = new List<Recetum>();
			OnCreated();
		}

		/// <summary>Gets or sets the Boleta field. </summary>
		public Nullable<System.Boolean> Boleta { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodPrestacionTipo field. </summary>
		public System.Int16 CodPrestacionTipo { get; set; }
		/// <summary>Gets or sets the Fecha field. </summary>
		public System.DateTime Fecha { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets or sets the Moneda field. </summary>
		public System.String? Moneda { get; set; }
		/// <summary>Gets or sets the Observaciones field. </summary>
		public System.String? Observaciones { get; set; }
		/// <summary>Gets the PrestacionId field. </summary>
		public System.Int32 PrestacionId => _prestacionId;
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.Afiliado - Afiliado.Prestacions (m:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.Moneda1 - Moneda.Prestacions (m:1)'</summary>
		public virtual Moneda? Moneda1 { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.PrestacionTipo - PrestacionTipo.Prestacions (m:1)'</summary>
		public virtual PrestacionTipo PrestacionTipo { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'Recetum.Prestacion - Prestacion.Receta (m:1)'</summary>
		public virtual List<Recetum> Receta { get; set; }
	}
}
