//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'PrestacionTipo'.</summary>
	public partial class PrestacionTipo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="PrestacionTipo"/> class.</summary>
		public PrestacionTipo() : base()
		{
			this.Prestacions = new List<Prestacion>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodPrestacionTipo field. </summary>
		public System.Int16 CodPrestacionTipo { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the FechaVigencia field. </summary>
		public Nullable<System.DateTime> FechaVigencia { get; set; }
		/// <summary>Gets or sets the ImporteTopeCasemed field. </summary>
		public Nullable<System.Double> ImporteTopeCasemed { get; set; }
		/// <summary>Gets or sets the ImporteTopeDisse field. </summary>
		public Nullable<System.Double> ImporteTopeDisse { get; set; }
		/// <summary>Gets or sets the Obs field. </summary>
		public System.String? Obs { get; set; }
		/// <summary>Gets or sets the PeriodoRenovacion field. </summary>
		public Nullable<System.Int16> PeriodoRenovacion { get; set; }
		/// <summary>Gets or sets the Receta field. </summary>
		public Nullable<System.Boolean> Receta { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Prestacion.PrestacionTipo - PrestacionTipo.Prestacions (m:1)'</summary>
		public virtual List<Prestacion> Prestacions { get; set; }
	}
}
