//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'PrimaFallecimiento'.</summary>
	public partial class PrimaFallecimiento : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="PrimaFallecimiento"/> class.</summary>
		public PrimaFallecimiento() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the FechaFallecimiento field. </summary>
		public Nullable<System.DateTime> FechaFallecimiento { get; set; }
		/// <summary>Gets or sets the FechaFirma field. </summary>
		public Nullable<System.DateTime> FechaFirma { get; set; }
		/// <summary>Gets or sets the FechaPago field. </summary>
		public Nullable<System.DateTime> FechaPago { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets or sets the Observaciones field. </summary>
		public System.String? Observaciones { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'PrimaFallecimiento.Afiliado - Afiliado.PrimaFallecimiento (1:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
	}
}
