//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'RecetaDistancium'.</summary>
	public partial class RecetaDistancium : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="RecetaDistancium"/> class.</summary>
		public RecetaDistancium() : base()
		{
			this.Receta = new List<Recetum>();
			this.CodRecetaDistancia = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the CodRecetaDistancia field. </summary>
		public System.String CodRecetaDistancia { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Recetum.RecetaDistancium - RecetaDistancium.Receta (m:1)'</summary>
		public virtual List<Recetum> Receta { get; set; }
	}
}
