//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Recetum'.</summary>
	public partial class Recetum : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _recetaId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Recetum"/> class.</summary>
		public Recetum() : base()
		{
			this.CodRecetaDistancia = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CilD field. </summary>
		public Nullable<System.Single> CilD { get; set; }
		/// <summary>Gets or sets the CilI field. </summary>
		public Nullable<System.Single> CilI { get; set; }
		/// <summary>Gets or sets the CodPrestacionTipo field. </summary>
		public System.Int16 CodPrestacionTipo { get; set; }
		/// <summary>Gets or sets the CodRecetaDistancia field. </summary>
		public System.String CodRecetaDistancia { get; set; }
		/// <summary>Gets or sets the EsfD field. </summary>
		public Nullable<System.Single> EsfD { get; set; }
		/// <summary>Gets or sets the EsfI field. </summary>
		public Nullable<System.Single> EsfI { get; set; }
		/// <summary>Gets or sets the Fecha field. </summary>
		public System.DateTime Fecha { get; set; }
		/// <summary>Gets or sets the PrestacionId field. </summary>
		public Nullable<System.Int32> PrestacionId { get; set; }
		/// <summary>Gets the RecetaId field. </summary>
		public System.Int32 RecetaId => _recetaId;
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Recetum.Prestacion - Prestacion.Receta (m:1)'</summary>
		public virtual Prestacion? Prestacion { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Recetum.RecetaDistancium - RecetaDistancium.Receta (m:1)'</summary>
		public virtual RecetaDistancium RecetaDistancium { get; set; } = null!;
	}
}
