//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'RegimenAporte'.</summary>
	public partial class RegimenAporte : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="RegimenAporte"/> class.</summary>
		public RegimenAporte() : base()
		{
			this.Empresas = new List<Empresa>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodRegimenAporte field. </summary>
		public System.Int16 CodRegimenAporte { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Porcentaje field. </summary>
		public Nullable<System.Int16> Porcentaje { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Empresa.RegimenAporte - RegimenAporte.Empresas (m:1)'</summary>
		public virtual List<Empresa> Empresas { get; set; }
	}
}
