//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'RegimenJubilatorio'.</summary>
	public partial class RegimenJubilatorio : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="RegimenJubilatorio"/> class.</summary>
		public RegimenJubilatorio() : base()
		{
			this.Afiliados = new List<Afiliado>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodRegimenJubilatorio field. </summary>
		public System.Byte CodRegimenJubilatorio { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Afiliado.RegimenJubilatorio - RegimenJubilatorio.Afiliados (m:1)'</summary>
		public virtual List<Afiliado> Afiliados { get; set; }
	}
}
