//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'ReintegroMutual'.</summary>
	public partial class ReintegroMutual : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _reintegroMutualId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="ReintegroMutual"/> class.</summary>
		public ReintegroMutual() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public System.Int16 Anio { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodMutualista field. </summary>
		public Nullable<System.Int16> CodMutualista { get; set; }
		/// <summary>Gets or sets the Fecha field. </summary>
		public Nullable<System.DateTime> Fecha { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Single> Importe { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public System.Int16 Mes { get; set; }
		/// <summary>Gets or sets the Observaciones field. </summary>
		public System.String? Observaciones { get; set; }
		/// <summary>Gets the ReintegroMutualId field. </summary>
		public System.Int32 ReintegroMutualId => _reintegroMutualId;
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'ReintegroMutual.Afiliado - Afiliado.ReintegroMutuals (m:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'ReintegroMutual.Mutualistum - Mutualistum.ReintegroMutuals (m:1)'</summary>
		public virtual Mutualistum? Mutualistum { get; set; }
	}
}
