//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SalidaTipo'.</summary>
	public partial class SalidaTipo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="SalidaTipo"/> class.</summary>
		public SalidaTipo() : base()
		{
			this.Certificacions = new List<Certificacion>();
			OnCreated();
		}

		/// <summary>Gets or sets the CodSalidaTipo field. </summary>
		public System.Int16 CodSalidaTipo { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Certificacion.SalidaTipo - SalidaTipo.Certificacions (m:1)'</summary>
		public virtual List<Certificacion> Certificacions { get; set; }
	}
}
