//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Seleccion'.</summary>
	public partial class Seleccion : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _seleccionId = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="Seleccion"/> class.</summary>
		public Seleccion() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Form field. </summary>
		public System.String? Form { get; set; }
		/// <summary>Gets or sets the Nombre field. </summary>
		public System.String? Nombre { get; set; }
		/// <summary>Gets the SeleccionId field. </summary>
		public System.Int32 SeleccionId => _seleccionId;
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the System field. </summary>
		public Nullable<System.Boolean> System { get; set; }
		/// <summary>Gets or sets the Txt field. </summary>
		public System.String? Txt { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
	}
}
