//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioItemCodAfiliado'.</summary>
	public partial class SubsidioItemCodAfiliado : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();
		private System.Int32 _subItmCodAfiId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="SubsidioItemCodAfiliado"/> class.</summary>
		public SubsidioItemCodAfiliado() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public Nullable<System.Int32> Ci { get; set; }
		/// <summary>Gets or sets the CodSubsidioItemCod field. </summary>
		public Nullable<System.Int16> CodSubsidioItemCod { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets the SubItmCodAfiId field. </summary>
		public System.Int32 SubItmCodAfiId => _subItmCodAfiId;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Gets or sets the Valor field. </summary>
		public Nullable<System.Double> Valor { get; set; }
		/// <summary>Gets or sets the Vigencia field. </summary>
		public Nullable<System.DateTime> Vigencia { get; set; }
	}
}
