//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioItemCod'.</summary>
	public partial class SubsidioItemCod : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="SubsidioItemCod"/> class.</summary>
		public SubsidioItemCod() : base()
		{
			this.SubsidioItems = new List<SubsidioItem>();
			OnCreated();
		}

		/// <summary>Gets or sets the AperturaXempresa field. </summary>
		public Nullable<System.Boolean> AperturaXempresa { get; set; }
		/// <summary>Gets or sets the CodSubsidioItemCod field. </summary>
		public System.Int16 CodSubsidioItemCod { get; set; }
		/// <summary>Gets or sets the Comparar field. </summary>
		public Nullable<System.Boolean> Comparar { get; set; }
		/// <summary>Gets or sets the CompararContra field. </summary>
		public Nullable<System.Byte> CompararContra { get; set; }
		/// <summary>Gets or sets the Descrip field. </summary>
		public System.String? Descrip { get; set; }
		/// <summary>Gets or sets the FechaBaja field. </summary>
		public Nullable<System.DateTime> FechaBaja { get; set; }
		/// <summary>Gets or sets the FechaVigencia field. </summary>
		public Nullable<System.DateTime> FechaVigencia { get; set; }
		/// <summary>Gets or sets the ModificaNominal field. </summary>
		public Nullable<System.Boolean> ModificaNominal { get; set; }
		/// <summary>Gets or sets the Operador field. </summary>
		public System.String? Operador { get; set; }
		/// <summary>Gets or sets the Procesar field. </summary>
		public Nullable<System.Boolean> Procesar { get; set; }
		/// <summary>Gets or sets the Signo field. </summary>
		public Nullable<System.Byte> Signo { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Tipo field. </summary>
		public System.String? Tipo { get; set; }
		/// <summary>Gets or sets the TipoComp field. </summary>
		public System.String? TipoComp { get; set; }
		/// <summary>Gets or sets the Valor field. </summary>
		public Nullable<System.Double> Valor { get; set; }
		/// <summary>Gets or sets the ValorMax field. </summary>
		public Nullable<System.Double> ValorMax { get; set; }
		/// <summary>Gets or sets the ValorMin field. </summary>
		public Nullable<System.Double> ValorMin { get; set; }
		/// <summary>Gets or sets the ValorTipo field. </summary>
		public System.String? ValorTipo { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItem.SubsidioItemCod - SubsidioItemCod.SubsidioItems (m:1)'</summary>
		public virtual List<SubsidioItem> SubsidioItems { get; set; }
	}
}
