//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioEnfermedad'.</summary>
	public partial class SubsidioEnfermedad : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();
		private System.Int32 _subsidioEnfermedadId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="SubsidioEnfermedad"/> class.</summary>
		public SubsidioEnfermedad() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Dias field. </summary>
		public Nullable<System.Byte> Dias { get; set; }
		/// <summary>Gets or sets the FechaFin field. </summary>
		public Nullable<System.DateTime> FechaFin { get; set; }
		/// <summary>Gets or sets the FechaFinSubsidio field. </summary>
		public Nullable<System.DateTime> FechaFinSubsidio { get; set; }
		/// <summary>Gets or sets the FechaIni field. </summary>
		public System.DateTime FechaIni { get; set; }
		/// <summary>Gets or sets the FechaIniSubsidio field. </summary>
		public Nullable<System.DateTime> FechaIniSubsidio { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets or sets the NroLlamado field. </summary>
		public Nullable<System.Int32> NroLlamado { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets the SubsidioEnfermedadId field. </summary>
		public System.Int32 SubsidioEnfermedadId => _subsidioEnfermedadId;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioEnfermedad.SubsidioCabezal - SubsidioCabezal.SubsidioEnfermedads (m:1)'</summary>
		public virtual SubsidioCabezal SubsidioCabezal { get; set; } = null!;
	}
}
