//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioCabezalEmpresa'.</summary>
	public partial class SubsidioCabezalEmpresa : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();
		private System.Int32 _subsidioCabezalempresaId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="SubsidioCabezalEmpresa"/> class.</summary>
		public SubsidioCabezalEmpresa() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets or sets the Dias field. </summary>
		public Nullable<System.Int16> Dias { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio { get; set; }
		/// <summary>Gets or sets the ImpAguinaldo field. </summary>
		public Nullable<System.Double> ImpAguinaldo { get; set; }
		/// <summary>Gets or sets the ImpLiquido field. </summary>
		public Nullable<System.Double> ImpLiquido { get; set; }
		/// <summary>Gets or sets the ImpNominal field. </summary>
		public Nullable<System.Double> ImpNominal { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets the SubsidioCabezalempresaId field. </summary>
		public System.Int32 SubsidioCabezalempresaId => _subsidioCabezalempresaId;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Gets or sets the ValorJornal field. </summary>
		public Nullable<System.Single> ValorJornal { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalEmpresa.Empresa - Empresa.SubsidioCabezalEmpresas (m:1)'</summary>
		public virtual Empresa Empresa { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalEmpresa.SubsidioCabezal - SubsidioCabezal.SubsidioCabezalEmpresas (m:1)'</summary>
		public virtual SubsidioCabezal SubsidioCabezal { get; set; } = null!;
	}
}
