//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioCabezal'.</summary>
	public partial class SubsidioCabezal : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _idSubsidio = default(System.Int32);
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="SubsidioCabezal"/> class.</summary>
		public SubsidioCabezal() : base()
		{
			this.SubsidioCabezalEmpresas = new List<SubsidioCabezalEmpresa>();
			this.SubsidioEnfermedads = new List<SubsidioEnfermedad>();
			this.SubsidioImponibles = new List<SubsidioImponible>();
			this.SubsidioItems = new List<SubsidioItem>();
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public Nullable<System.Int16> Anio { get; set; }
		/// <summary>Gets or sets the Ci field. </summary>
		public Nullable<System.Int32> Ci { get; set; }
		/// <summary>Gets or sets the CodBanco field. </summary>
		public Nullable<System.Int32> CodBanco { get; set; }
		/// <summary>Gets or sets the Dias field. </summary>
		public Nullable<System.Int16> Dias { get; set; }
		/// <summary>Gets or sets the FechaPago field. </summary>
		public Nullable<System.DateTime> FechaPago { get; set; }
		/// <summary>Gets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio => _idSubsidio;
		/// <summary>Gets or sets the ImpAguinaldo field. </summary>
		public Nullable<System.Double> ImpAguinaldo { get; set; }
		/// <summary>Gets or sets the ImpLiquido field. </summary>
		public Nullable<System.Double> ImpLiquido { get; set; }
		/// <summary>Gets or sets the ImpNominal field. </summary>
		public Nullable<System.Double> ImpNominal { get; set; }
		/// <summary>Gets or sets the Liquidar field. </summary>
		public Nullable<System.Boolean> Liquidar { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public Nullable<System.Byte> Mes { get; set; }
		/// <summary>Gets or sets the NroCuenta field. </summary>
		public System.String? NroCuenta { get; set; }
		/// <summary>Gets or sets the NroRecibo field. </summary>
		public Nullable<System.Int32> NroRecibo { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Gets or sets the ValorJornal field. </summary>
		public Nullable<System.Single> ValorJornal { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezal.Afiliado - Afiliado.SubsidioCabezals (m:1)'</summary>
		public virtual Afiliado? Afiliado { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalBp.SubsidioCabezal - SubsidioCabezal.SubsidioCabezalBp (1:1)'</summary>
		public virtual SubsidioCabezalBp? SubsidioCabezalBp { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalEmpresa.SubsidioCabezal - SubsidioCabezal.SubsidioCabezalEmpresas (m:1)'</summary>
		public virtual List<SubsidioCabezalEmpresa> SubsidioCabezalEmpresas { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioEnfermedad.SubsidioCabezal - SubsidioCabezal.SubsidioEnfermedads (m:1)'</summary>
		public virtual List<SubsidioEnfermedad> SubsidioEnfermedads { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioImponible.SubsidioCabezal - SubsidioCabezal.SubsidioImponibles (m:1)'</summary>
		public virtual List<SubsidioImponible> SubsidioImponibles { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItem.SubsidioCabezal - SubsidioCabezal.SubsidioItems (m:1)'</summary>
		public virtual List<SubsidioItem> SubsidioItems { get; set; }
	}
}
