//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioCabezalBp'.</summary>
	public partial class SubsidioCabezalBp : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="SubsidioCabezalBp"/> class.</summary>
		public SubsidioCabezalBp() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AguinaldoBps field. </summary>
		public Nullable<System.Double> AguinaldoBps { get; set; }
		/// <summary>Gets or sets the DiasBps field. </summary>
		public Nullable<System.Int32> DiasBps { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio { get; set; }
		/// <summary>Gets or sets the LiquidoBps field. </summary>
		public Nullable<System.Double> LiquidoBps { get; set; }
		/// <summary>Gets or sets the LiquidoPagar field. </summary>
		public Nullable<System.Double> LiquidoPagar { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioCabezalBp.SubsidioCabezal - SubsidioCabezal.SubsidioCabezalBp (1:1)'</summary>
		public virtual SubsidioCabezal SubsidioCabezal { get; set; } = null!;
	}
}
