//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioItemEmpresa'.</summary>
	public partial class SubsidioItemEmpresa : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();
		private System.Int32 _subsidioItemEmpresaId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="SubsidioItemEmpresa"/> class.</summary>
		public SubsidioItemEmpresa() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets or sets the CodSubsidioItemCod field. </summary>
		public System.Int16 CodSubsidioItemCod { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Single> Importe { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets the SubsidioItemEmpresaId field. </summary>
		public System.Int32 SubsidioItemEmpresaId => _subsidioItemEmpresaId;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItemEmpresa.Empresa - Empresa.SubsidioItemEmpresas (m:1)'</summary>
		public virtual Empresa Empresa { get; set; } = null!;
	}
}
