//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioItem'.</summary>
	public partial class SubsidioItem : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();
		private System.Int32 _subsidioItemId = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="SubsidioItem"/> class.</summary>
		public SubsidioItem() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AbiEmp field. </summary>
		public Nullable<System.Boolean> AbiEmp { get; set; }
		/// <summary>Gets or sets the CodSubsidioItemCod field. </summary>
		public System.Int16 CodSubsidioItemCod { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public System.Int32 IdSubsidio { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets the SubsidioItemId field. </summary>
		public System.Int32 SubsidioItemId => _subsidioItemId;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItem.SubsidioCabezal - SubsidioCabezal.SubsidioItems (m:1)'</summary>
		public virtual SubsidioCabezal SubsidioCabezal { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioItem.SubsidioItemCod - SubsidioItemCod.SubsidioItems (m:1)'</summary>
		public virtual SubsidioItemCod SubsidioItemCod { get; set; } = null!;
	}
}
