//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'SubsidioImponible'.</summary>
	public partial class SubsidioImponible : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Byte[] _ssmaTimeStamp = Array.Empty<System.Byte>();

		/// <summary>Initializes a new instance of the <see cref="SubsidioImponible"/> class.</summary>
		public SubsidioImponible() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Anio field. </summary>
		public Nullable<System.Int16> Anio { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public Nullable<System.Int16> CodEmpresa { get; set; }
		/// <summary>Gets or sets the Dias field. </summary>
		public Nullable<System.Int16> Dias { get; set; }
		/// <summary>Gets or sets the IdSubsidio field. </summary>
		public Nullable<System.Int32> IdSubsidio { get; set; }
		/// <summary>Gets or sets the Importe field. </summary>
		public Nullable<System.Double> Importe { get; set; }
		/// <summary>Gets or sets the Mes field. </summary>
		public Nullable<System.Byte> Mes { get; set; }
		/// <summary>Gets the SsmaTimeStamp field. </summary>
		public System.Byte[] SsmaTimeStamp => _ssmaTimeStamp;
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioImponible.Empresa - Empresa.SubsidioImponibles (m:1)'</summary>
		public virtual Empresa? Empresa { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'SubsidioImponible.SubsidioCabezal - SubsidioCabezal.SubsidioImponibles (m:1)'</summary>
		public virtual SubsidioCabezal? SubsidioCabezal { get; set; }
	}
}
