//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'Trabaja'.</summary>
	public partial class Trabaja : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _idTrabaja = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Trabaja"/> class.</summary>
		public Trabaja() : base()
		{
			this.Imponibles = new List<Imponible>();
			OnCreated();
		}

		/// <summary>Gets or sets the Ci field. </summary>
		public System.Int32 Ci { get; set; }
		/// <summary>Gets or sets the CodBajaMotivo field. </summary>
		public Nullable<System.Int32> CodBajaMotivo { get; set; }
		/// <summary>Gets or sets the CodEmpresa field. </summary>
		public System.Int16 CodEmpresa { get; set; }
		/// <summary>Gets or sets the FechaBaja field. </summary>
		public Nullable<System.DateTime> FechaBaja { get; set; }
		/// <summary>Gets or sets the FechaIngCasemed field. </summary>
		public Nullable<System.DateTime> FechaIngCasemed { get; set; }
		/// <summary>Gets or sets the FechaIngreso field. </summary>
		public System.DateTime FechaIngreso { get; set; }
		/// <summary>Gets the IdTrabaja field. </summary>
		public System.Int32 IdTrabaja => _idTrabaja;
		/// <summary>Gets or sets the NroFichaEmpresa field. </summary>
		public System.String? NroFichaEmpresa { get; set; }
		/// <summary>Gets or sets the Ts field. </summary>
		public Nullable<System.DateTime> Ts { get; set; }
		/// <summary>Gets or sets the Usr field. </summary>
		public System.String? Usr { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.Afiliado - Afiliado.Trabajas (m:1)'</summary>
		public virtual Afiliado Afiliado { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.BajaMotivo - BajaMotivo.Trabajas (m:1)'</summary>
		public virtual BajaMotivo? BajaMotivo { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Trabaja.Empresa - Empresa.Trabajas (m:1)'</summary>
		public virtual Empresa Empresa { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'Imponible.Trabaja - Trabaja.Imponibles (m:1)'</summary>
		public virtual List<Imponible> Imponibles { get; set; }
	}
}
