//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace SgpaNew.EntityClasses
{
	/// <summary>Class which represents the entity 'XUsrParam'.</summary>
	public partial class XUsrParam : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _idUsuario = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="XUsrParam"/> class.</summary>
		public XUsrParam() : base()
		{
			this.Clave = string.Empty;
			this.Login = string.Empty;
			OnCreated();
		}

		/// <summary>Gets or sets the Clave field. </summary>
		public System.String Clave { get; set; }
		/// <summary>Gets the IdUsuario field. </summary>
		public System.Int32 IdUsuario => _idUsuario;
		/// <summary>Gets or sets the Login field. </summary>
		public System.String Login { get; set; }
		/// <summary>Gets or sets the Orden field. </summary>
		public System.Int16 Orden { get; set; }
		/// <summary>Gets or sets the Value1 field. </summary>
		public System.String? Value1 { get; set; }
		/// <summary>Gets or sets the Value2 field. </summary>
		public System.String? Value2 { get; set; }
		/// <summary>Gets or sets the Value3 field. </summary>
		public System.String? Value3 { get; set; }
		/// <summary>Gets or sets the Value4 field. </summary>
		public System.String? Value4 { get; set; }
		/// <summary>Gets or sets the Value5 field. </summary>
		public System.String? Value5 { get; set; }
	}
}
