[General]
Nom_MDB=Sgpa.MDB
Nom_MDB_Servidor=SgpaServ.Mdb
Nom_MDB_Seguridad=Segurida.MDB
Nom_MDB_Seguridad_Servidor=SeguServ.Mdb
Nom_Dir_Servidor=c:\gestion\SGPA\DATA
Nom_Dir_Version=c:\gestion\SGPA\VERSION
;Nom_Dir_Servidor=d:\winnt\gestion\SGPA\DATA
;Nom_Dir_Version=d:\winnt\gestion\SGPA\VERSION
;Nom_Dir_Servidor=c:\windows\gestion\SGPA\DATA
;Nom_Dir_Version=c:\windows\gestion\SGPA\VERSION
Automatico=True
Release=1

[Exes]
Programa=Sgpa.EXE
Seguridad=Segurida.exe
[Copias]