//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using SgpaNew.EntityClasses;

namespace SgpaNew
{
	/// <summary>Class which represents the DataContext for the project / group 'SgpaNew'</summary>
	public partial class SgpaNewDataContext : DbContext
	{
		partial void OnModelCreatingComplete();

		/// <summary>Constructor which accepts an already setup DbContextOptions instance</summary>
		/// <param name="options">The DbContextOptions object to use</param>
		public SgpaNewDataContext(DbContextOptions<SgpaNewDataContext> options) : base(options) {}
		
		/// <summary>Empty constructor which relies on OnConfiguring being overriden</summary>
		public SgpaNewDataContext() : base() {}
		
		/// <inheritdoc/>
		public override int SaveChanges(bool acceptAllChangesOnSuccess)
		{
			CheckReadonlyEntities();
			return base.SaveChanges(acceptAllChangesOnSuccess);
		}

		/// <inheritdoc/>
		public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken())
		{
			CheckReadonlyEntities();
			return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
		}
		
		/// <inheritdoc/>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			new SgpaNewModelBuilder().BuildModel(modelBuilder);
			OnModelCreatingComplete();
		}

		private void CheckReadonlyEntities()
		{
			var namesOfChangedReadOnlyEntities = this.ChangeTracker.Entries().Where(e => e.Metadata.IsReadOnly() && e.State != EntityState.Unchanged).Select(e => e.Metadata.Name).Distinct().ToList();
			if(namesOfChangedReadOnlyEntities.Any())
			{
				throw new InvalidOperationException($"Attempted to save the following read-only entitie(s): {string.Join(",", namesOfChangedReadOnlyEntities)}");
			}
		}

		/// <summary>Gets an object query for the entity set 'AdPreJub', containing entity type 'AdPreJub'</summary>
		public DbSet<AdPreJub> AdPreJubs { get; set; } 
		/// <summary>Gets an object query for the entity set 'AdPreJubPago', containing entity type 'AdPreJubPago'</summary>
		public DbSet<AdPreJubPago> AdPreJubPagos { get; set; } 
		/// <summary>Gets an object query for the entity set 'AfeccionGrupo', containing entity type 'AfeccionGrupo'</summary>
		public DbSet<AfeccionGrupo> AfeccionGrupos { get; set; } 
		/// <summary>Gets an object query for the entity set 'AfeccionTipo', containing entity type 'AfeccionTipo'</summary>
		public DbSet<AfeccionTipo> AfeccionTipos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Afiliado', containing entity type 'Afiliado'</summary>
		public DbSet<Afiliado> Afiliados { get; set; } 
		/// <summary>Gets an object query for the entity set 'AfiliadoApunte', containing entity type 'AfiliadoApunte'</summary>
		public DbSet<AfiliadoApunte> AfiliadoApuntes { get; set; } 
		/// <summary>Gets an object query for the entity set 'AfiliadoEspecialidad', containing entity type 'AfiliadoEspecialidad'</summary>
		public DbSet<AfiliadoEspecialidad> AfiliadoEspecialidads { get; set; } 
		/// <summary>Gets an object query for the entity set 'AporteTipo', containing entity type 'AporteTipo'</summary>
		public DbSet<AporteTipo> AporteTipos { get; set; } 
		/// <summary>Gets an object query for the entity set 'BajaMotivo', containing entity type 'BajaMotivo'</summary>
		public DbSet<BajaMotivo> BajaMotivos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Banco', containing entity type 'Banco'</summary>
		public DbSet<Banco> Bancos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Certificacion', containing entity type 'Certificacion'</summary>
		public DbSet<Certificacion> Certificacions { get; set; } 
		/// <summary>Gets an object query for the entity set 'CertificacionProrroga', containing entity type 'CertificacionProrroga'</summary>
		public DbSet<CertificacionProrroga> CertificacionProrrogas { get; set; } 
		/// <summary>Gets an object query for the entity set 'Certificador', containing entity type 'Certificador'</summary>
		public DbSet<Certificador> Certificadors { get; set; } 
		/// <summary>Gets an object query for the entity set 'Ctasbrou', containing entity type 'Ctasbrou'</summary>
		public DbSet<Ctasbrou> Ctasbrous { get; set; } 
		/// <summary>Gets an object query for the entity set 'Cuentum', containing entity type 'Cuentum'</summary>
		public DbSet<Cuentum> Cuenta { get; set; } 
		/// <summary>Gets an object query for the entity set 'Departamento', containing entity type 'Departamento'</summary>
		public DbSet<Departamento> Departamentos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Discount', containing entity type 'Discount'</summary>
		public DbSet<Discount> Discounts { get; set; } 
		/// <summary>Gets an object query for the entity set 'Empresa', containing entity type 'Empresa'</summary>
		public DbSet<Empresa> Empresas { get; set; } 
		/// <summary>Gets an object query for the entity set 'EmpresaPago', containing entity type 'EmpresaPago'</summary>
		public DbSet<EmpresaPago> EmpresaPagos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Especialidad', containing entity type 'Especialidad'</summary>
		public DbSet<Especialidad> Especialidads { get; set; } 
		/// <summary>Gets an object query for the entity set 'FormaPago', containing entity type 'FormaPago'</summary>
		public DbSet<FormaPago> FormaPagos { get; set; } 
		/// <summary>Gets an object query for the entity set 'FranjaIrpf', containing entity type 'FranjaIrpf'</summary>
		public DbSet<FranjaIrpf> FranjaIrpfs { get; set; } 
		/// <summary>Gets an object query for the entity set 'Imp', containing entity type 'Imp'</summary>
		public DbSet<Imp> Imps { get; set; } 
		/// <summary>Gets an object query for the entity set 'Imponible', containing entity type 'Imponible'</summary>
		public DbSet<Imponible> Imponibles { get; set; } 
		/// <summary>Gets an object query for the entity set 'InformeEstadistico', containing entity type 'InformeEstadistico'</summary>
		public DbSet<InformeEstadistico> InformeEstadisticos { get; set; } 
		/// <summary>Gets an object query for the entity set 'LiquidacionBp', containing entity type 'LiquidacionBp'</summary>
		public DbSet<LiquidacionBp> LiquidacionBps { get; set; } 
		/// <summary>Gets an object query for the entity set 'MaeFun', containing entity type 'MaeFun'</summary>
		public DbSet<MaeFun> MaeFuns { get; set; } 
		/// <summary>Gets an object query for the entity set 'Moneda', containing entity type 'Moneda'</summary>
		public DbSet<Moneda> Monedas { get; set; } 
		/// <summary>Gets an object query for the entity set 'Mutualistum', containing entity type 'Mutualistum'</summary>
		public DbSet<Mutualistum> Mutualista { get; set; } 
		/// <summary>Gets an object query for the entity set 'NoCargadoHl', containing entity type 'NoCargadoHl'</summary>
		public DbSet<NoCargadoHl> NoCargadoHls { get; set; } 
		/// <summary>Gets an object query for the entity set 'Parametro', containing entity type 'Parametro'</summary>
		public DbSet<Parametro> Parametros { get; set; } 
		/// <summary>Gets an object query for the entity set 'Patologium', containing entity type 'Patologium'</summary>
		public DbSet<Patologium> Patologia { get; set; } 
		/// <summary>Gets an object query for the entity set 'Prestacion', containing entity type 'Prestacion'</summary>
		public DbSet<Prestacion> Prestacions { get; set; } 
		/// <summary>Gets an object query for the entity set 'PrestacionTipo', containing entity type 'PrestacionTipo'</summary>
		public DbSet<PrestacionTipo> PrestacionTipos { get; set; } 
		/// <summary>Gets an object query for the entity set 'PrimaFallecimiento', containing entity type 'PrimaFallecimiento'</summary>
		public DbSet<PrimaFallecimiento> PrimaFallecimientos { get; set; } 
		/// <summary>Gets an object query for the entity set 'RecetaDistancium', containing entity type 'RecetaDistancium'</summary>
		public DbSet<RecetaDistancium> RecetaDistancia { get; set; } 
		/// <summary>Gets an object query for the entity set 'Recetum', containing entity type 'Recetum'</summary>
		public DbSet<Recetum> Receta { get; set; } 
		/// <summary>Gets an object query for the entity set 'RegimenAporte', containing entity type 'RegimenAporte'</summary>
		public DbSet<RegimenAporte> RegimenAportes { get; set; } 
		/// <summary>Gets an object query for the entity set 'RegimenJubilatorio', containing entity type 'RegimenJubilatorio'</summary>
		public DbSet<RegimenJubilatorio> RegimenJubilatorios { get; set; } 
		/// <summary>Gets an object query for the entity set 'ReintegroMutual', containing entity type 'ReintegroMutual'</summary>
		public DbSet<ReintegroMutual> ReintegroMutuals { get; set; } 
		/// <summary>Gets an object query for the entity set 'SalidaTipo', containing entity type 'SalidaTipo'</summary>
		public DbSet<SalidaTipo> SalidaTipos { get; set; } 
		/// <summary>Gets an object query for the entity set 'Seleccion', containing entity type 'Seleccion'</summary>
		public DbSet<Seleccion> Seleccions { get; set; } 
		/// <summary>Gets an object query for the entity set 'SituacionMutual', containing entity type 'SituacionMutual'</summary>
		public DbSet<SituacionMutual> SituacionMutuals { get; set; } 
		/// <summary>Gets an object query for the entity set 'SituacionPago', containing entity type 'SituacionPago'</summary>
		public DbSet<SituacionPago> SituacionPagos { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioCabezal', containing entity type 'SubsidioCabezal'</summary>
		public DbSet<SubsidioCabezal> SubsidioCabezals { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioCabezalBp', containing entity type 'SubsidioCabezalBp'</summary>
		public DbSet<SubsidioCabezalBp> SubsidioCabezalBps { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioCabezalEmpresa', containing entity type 'SubsidioCabezalEmpresa'</summary>
		public DbSet<SubsidioCabezalEmpresa> SubsidioCabezalEmpresas { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioEnfermedad', containing entity type 'SubsidioEnfermedad'</summary>
		public DbSet<SubsidioEnfermedad> SubsidioEnfermedads { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioImponible', containing entity type 'SubsidioImponible'</summary>
		public DbSet<SubsidioImponible> SubsidioImponibles { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioItem', containing entity type 'SubsidioItem'</summary>
		public DbSet<SubsidioItem> SubsidioItems { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioItemCod', containing entity type 'SubsidioItemCod'</summary>
		public DbSet<SubsidioItemCod> SubsidioItemCods { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioItemCodAfiliado', containing entity type 'SubsidioItemCodAfiliado'</summary>
		public DbSet<SubsidioItemCodAfiliado> SubsidioItemCodAfiliados { get; set; } 
		/// <summary>Gets an object query for the entity set 'SubsidioItemEmpresa', containing entity type 'SubsidioItemEmpresa'</summary>
		public DbSet<SubsidioItemEmpresa> SubsidioItemEmpresas { get; set; } 
		/// <summary>Gets an object query for the entity set 'Trabaja', containing entity type 'Trabaja'</summary>
		public DbSet<Trabaja> Trabajas { get; set; } 
		/// <summary>Gets an object query for the entity set 'XUsrParam', containing entity type 'XUsrParam'</summary>
		public DbSet<XUsrParam> XUsrParams { get; set; } 
	}
}
