//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SgpaNew.EntityClasses;

namespace SgpaNew
{
	/// <summary>Model builder class for code first development.</summary>
	public partial class SgpaNewModelBuilder
	{
		/// <summary>Builds the model defined in this class with the modelbuilder specified. Called from the generated DbContext</summary>
		/// <param name="modelBuilder">The model builder to build the model with.</param>
		public virtual void BuildModel(ModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema("dbo");
			MapAdPreJub(modelBuilder.Entity<AdPreJub>());
			MapAdPreJubPago(modelBuilder.Entity<AdPreJubPago>());
			MapAfeccionGrupo(modelBuilder.Entity<AfeccionGrupo>());
			MapAfeccionTipo(modelBuilder.Entity<AfeccionTipo>());
			MapAfiliado(modelBuilder.Entity<Afiliado>());
			MapAfiliadoApunte(modelBuilder.Entity<AfiliadoApunte>());
			MapAfiliadoEspecialidad(modelBuilder.Entity<AfiliadoEspecialidad>());
			MapAporteTipo(modelBuilder.Entity<AporteTipo>());
			MapBajaMotivo(modelBuilder.Entity<BajaMotivo>());
			MapBanco(modelBuilder.Entity<Banco>());
			MapCertificacion(modelBuilder.Entity<Certificacion>());
			MapCertificacionProrroga(modelBuilder.Entity<CertificacionProrroga>());
			MapCertificador(modelBuilder.Entity<Certificador>());
			MapCtasbrou(modelBuilder.Entity<Ctasbrou>());
			MapCuentum(modelBuilder.Entity<Cuentum>().HasNoKey());
			MapDepartamento(modelBuilder.Entity<Departamento>());
			MapDiscount(modelBuilder.Entity<Discount>().HasNoKey());
			MapEmpresa(modelBuilder.Entity<Empresa>());
			MapEmpresaPago(modelBuilder.Entity<EmpresaPago>());
			MapEspecialidad(modelBuilder.Entity<Especialidad>());
			MapFormaPago(modelBuilder.Entity<FormaPago>());
			MapFranjaIrpf(modelBuilder.Entity<FranjaIrpf>());
			MapImp(modelBuilder.Entity<Imp>().HasNoKey());
			MapImponible(modelBuilder.Entity<Imponible>());
			MapInformeEstadistico(modelBuilder.Entity<InformeEstadistico>());
			MapLiquidacionBp(modelBuilder.Entity<LiquidacionBp>());
			MapMaeFun(modelBuilder.Entity<MaeFun>());
			MapMoneda(modelBuilder.Entity<Moneda>());
			MapMutualistum(modelBuilder.Entity<Mutualistum>());
			MapNoCargadoHl(modelBuilder.Entity<NoCargadoHl>());
			MapParametro(modelBuilder.Entity<Parametro>().HasNoKey());
			MapPatologium(modelBuilder.Entity<Patologium>());
			MapPrestacion(modelBuilder.Entity<Prestacion>());
			MapPrestacionTipo(modelBuilder.Entity<PrestacionTipo>());
			MapPrimaFallecimiento(modelBuilder.Entity<PrimaFallecimiento>());
			MapRecetaDistancium(modelBuilder.Entity<RecetaDistancium>());
			MapRecetum(modelBuilder.Entity<Recetum>());
			MapRegimenAporte(modelBuilder.Entity<RegimenAporte>());
			MapRegimenJubilatorio(modelBuilder.Entity<RegimenJubilatorio>());
			MapReintegroMutual(modelBuilder.Entity<ReintegroMutual>());
			MapSalidaTipo(modelBuilder.Entity<SalidaTipo>());
			MapSeleccion(modelBuilder.Entity<Seleccion>());
			MapSituacionMutual(modelBuilder.Entity<SituacionMutual>());
			MapSituacionPago(modelBuilder.Entity<SituacionPago>());
			MapSubsidioCabezal(modelBuilder.Entity<SubsidioCabezal>());
			MapSubsidioCabezalBp(modelBuilder.Entity<SubsidioCabezalBp>());
			MapSubsidioCabezalEmpresa(modelBuilder.Entity<SubsidioCabezalEmpresa>());
			MapSubsidioEnfermedad(modelBuilder.Entity<SubsidioEnfermedad>());
			MapSubsidioImponible(modelBuilder.Entity<SubsidioImponible>().HasNoKey());
			MapSubsidioItem(modelBuilder.Entity<SubsidioItem>());
			MapSubsidioItemCod(modelBuilder.Entity<SubsidioItemCod>());
			MapSubsidioItemCodAfiliado(modelBuilder.Entity<SubsidioItemCodAfiliado>());
			MapSubsidioItemEmpresa(modelBuilder.Entity<SubsidioItemEmpresa>());
			MapTrabaja(modelBuilder.Entity<Trabaja>());
			MapXUsrParam(modelBuilder.Entity<XUsrParam>());
		}

		/// <summary>Defines the mapping information for the entity 'AdPreJub'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAdPreJub(EntityTypeBuilder<AdPreJub> config)
		{
			config.ToTable("AdPreJub");
			config.HasKey(t => t.Ci);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.FechaPresentacion);
			config.Property(t => t.ImporteMensual);
			config.Property(t => t.FechaJubilacion);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Afiliado).WithOne(t => t.AdPreJub).HasForeignKey<AdPreJub>(t => t.Ci);
		}

		/// <summary>Defines the mapping information for the entity 'AdPreJubPago'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAdPreJubPago(EntityTypeBuilder<AdPreJubPago> config)
		{
			config.ToTable("AdPreJubPago");
			config.HasKey(t => t.AdPreJubPagoId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Fecha);
			config.Property(t => t.Importe);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.AdPreJubPagoId).ValueGeneratedOnAdd();
			config.HasOne(t => t.AdPreJub).WithMany(t => t.AdPreJubPagos).HasForeignKey(t => t.Ci);
		}

		/// <summary>Defines the mapping information for the entity 'AfeccionGrupo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAfeccionGrupo(EntityTypeBuilder<AfeccionGrupo> config)
		{
			config.ToTable("AfeccionGrupo");
			config.HasKey(t => t.CodAfeccionGrupo);
			config.Property(t => t.CodAfeccionGrupo);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.CodPatologia);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.HasOne(t => t.Patologium).WithMany(t => t.AfeccionGrupos).HasForeignKey(t => t.CodPatologia);
		}

		/// <summary>Defines the mapping information for the entity 'AfeccionTipo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAfeccionTipo(EntityTypeBuilder<AfeccionTipo> config)
		{
			config.ToTable("AfeccionTipo");
			config.HasKey(t => t.CodAfeccionTipo);
			config.Property(t => t.CodAfeccionTipo);
			config.Property(t => t.Descrip).HasMaxLength(200);
			config.Property(t => t.CodAfeccionGrupo);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.CodDiameg);
			config.HasOne(t => t.AfeccionGrupo).WithMany(t => t.AfeccionTipos).HasForeignKey(t => t.CodAfeccionGrupo);
		}

		/// <summary>Defines the mapping information for the entity 'Afiliado'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAfiliado(EntityTypeBuilder<Afiliado> config)
		{
			config.ToTable("Afiliado");
			config.HasKey(t => t.Ci);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Nombres).HasMaxLength(50);
			config.Property(t => t.Apellido1).HasMaxLength(30);
			config.Property(t => t.Apellido2).HasMaxLength(30);
			config.Property(t => t.FechaNacimiento);
			config.Property(t => t.Sexo).HasMaxLength(1);
			config.Property(t => t.Direccion).HasMaxLength(100);
			config.Property(t => t.Telefono).HasMaxLength(25);
			config.Property(t => t.Email).HasColumnName("EMail").HasMaxLength(100);
			config.Property(t => t.CodMutualista);
			config.Property(t => t.FechaIngMutualista);
			config.Property(t => t.FechaBajaMutualista);
			config.Property(t => t.NroSocioMutualista).HasMaxLength(12);
			config.Property(t => t.CodRegimenJubilatorio);
			config.Property(t => t.CodDepartamento).HasMaxLength(3);
			config.Property(t => t.PagaMutualista);
			config.Property(t => t.CodSituacionMutual).HasMaxLength(2);
			config.Property(t => t.CodBanco);
			config.Property(t => t.NroCuenta).HasMaxLength(50);
			config.Property(t => t.NroFunCuenta).HasMaxLength(50);
			config.Property(t => t.Movil).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Banco).WithMany(t => t.Afiliados).HasForeignKey(t => t.CodBanco);
			config.HasOne(t => t.Mutualistum).WithMany(t => t.Afiliados).HasForeignKey(t => t.CodMutualista);
			config.HasOne(t => t.RegimenJubilatorio).WithMany(t => t.Afiliados).HasForeignKey(t => t.CodRegimenJubilatorio);
		}

		/// <summary>Defines the mapping information for the entity 'AfiliadoApunte'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAfiliadoApunte(EntityTypeBuilder<AfiliadoApunte> config)
		{
			config.ToTable("AfiliadoApunte");
			config.HasKey(t => t.AfiliadoApunteId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Fecha);
			config.Property(t => t.Descrip);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.AfiliadoApunteId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Afiliado).WithMany(t => t.AfiliadoApuntes).HasForeignKey(t => t.Ci);
		}

		/// <summary>Defines the mapping information for the entity 'AfiliadoEspecialidad'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAfiliadoEspecialidad(EntityTypeBuilder<AfiliadoEspecialidad> config)
		{
			config.ToTable("AfiliadoEspecialidad");
			config.HasKey(t => t.AfiliadoEspecialidadId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.CodEspecialidad);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.AfiliadoEspecialidadId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Afiliado).WithMany(t => t.AfiliadoEspecialidads).HasForeignKey(t => t.Ci);
			config.HasOne(t => t.Especialidad).WithMany(t => t.AfiliadoEspecialidads).HasForeignKey(t => t.CodEspecialidad).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'AporteTipo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapAporteTipo(EntityTypeBuilder<AporteTipo> config)
		{
			config.ToTable("AporteTipo");
			config.HasKey(t => t.CodAporteTipo);
			config.Property(t => t.CodAporteTipo).HasMaxLength(3);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'BajaMotivo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapBajaMotivo(EntityTypeBuilder<BajaMotivo> config)
		{
			config.ToTable("BajaMotivo");
			config.HasKey(t => t.CodBajaMotivo);
			config.Property(t => t.CodBajaMotivo);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'Banco'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapBanco(EntityTypeBuilder<Banco> config)
		{
			config.ToTable("Banco");
			config.HasKey(t => t.CodBanco);
			config.Property(t => t.CodBanco);
			config.Property(t => t.Descripcion).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'Certificacion'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapCertificacion(EntityTypeBuilder<Certificacion> config)
		{
			config.ToTable("Certificacion");
			config.HasKey(t => t.NroLlamado);
			config.Property(t => t.NroLlamado);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.NroRecibo);
			config.Property(t => t.FechaRecibido);
			config.Property(t => t.FechaCertificacion);
			config.Property(t => t.FechaIni);
			config.Property(t => t.FechaFin);
			config.Property(t => t.CodAfeccionTipo);
			config.Property(t => t.CodCertificador);
			config.Property(t => t.CodSalidaTipo);
			config.Property(t => t.Efectiva);
			config.Property(t => t.Indicaciones);
			config.Property(t => t.ImporteDeducible);
			config.Property(t => t.Trabaja);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.AfeccionTipo).WithMany(t => t.Certificacions).HasForeignKey(t => t.CodAfeccionTipo);
			config.HasOne(t => t.Afiliado).WithMany(t => t.Certificacions).HasForeignKey(t => t.Ci);
			config.HasOne(t => t.Certificador).WithMany(t => t.Certificacions).HasForeignKey(t => t.CodCertificador);
			config.HasOne(t => t.SalidaTipo).WithMany(t => t.Certificacions).HasForeignKey(t => t.CodSalidaTipo);
		}

		/// <summary>Defines the mapping information for the entity 'CertificacionProrroga'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapCertificacionProrroga(EntityTypeBuilder<CertificacionProrroga> config)
		{
			config.ToTable("CertificacionProrroga");
			config.HasKey(t => t.CertificacionProrrogaId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Fecha);
			config.Property(t => t.Dias);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.CertificacionProrrogaId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Afiliado).WithMany(t => t.CertificacionProrrogas).HasForeignKey(t => t.Ci).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'Certificador'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapCertificador(EntityTypeBuilder<Certificador> config)
		{
			config.ToTable("Certificador");
			config.HasKey(t => t.CodCertificador);
			config.Property(t => t.CodCertificador);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Direccion).HasMaxLength(50);
			config.Property(t => t.Telefono).HasMaxLength(25);
			config.Property(t => t.Fax).HasMaxLength(25);
			config.Property(t => t.Bip).HasMaxLength(25);
			config.Property(t => t.CobraLlamado);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Ctasbrou'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapCtasbrou(EntityTypeBuilder<Ctasbrou> config)
		{
			config.ToTable("CTASBROU");
			config.HasKey(t => t.Ci);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Cta).HasMaxLength(50);
		}

		/// <summary>Defines the mapping information for the entity 'Cuentum'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapCuentum(EntityTypeBuilder<Cuentum> config)
		{
			config.ToTable("Cuenta");
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.CodBanco);
			config.Property(t => t.NroCuenta).HasMaxLength(50);
		}

		/// <summary>Defines the mapping information for the entity 'Departamento'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapDepartamento(EntityTypeBuilder<Departamento> config)
		{
			config.ToTable("Departamento");
			config.HasKey(t => t.CodDepartamento);
			config.Property(t => t.CodDepartamento).HasMaxLength(3);
			config.Property(t => t.Descrip).HasMaxLength(50);
		}

		/// <summary>Defines the mapping information for the entity 'Discount'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapDiscount(EntityTypeBuilder<Discount> config)
		{
			config.ToTable("DISCOUNT");
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Ficha).HasColumnName("FICHA");
			config.Property(t => t.NombreYApellido).HasColumnName("NOMBRE Y APELLIDO").HasMaxLength(255);
			config.Property(t => t.NºCuenta).HasColumnName("Nº CUENTA");
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Empresa'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapEmpresa(EntityTypeBuilder<Empresa> config)
		{
			config.ToTable("Empresa");
			config.HasKey(t => t.CodEmpresa);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Nombre).HasMaxLength(50);
			config.Property(t => t.Direccion).HasMaxLength(50);
			config.Property(t => t.Telefono).HasMaxLength(25);
			config.Property(t => t.Fax).HasMaxLength(25);
			config.Property(t => t.Email).HasColumnName("EMail").HasMaxLength(25);
			config.Property(t => t.AporteCasemed);
			config.Property(t => t.AporteAguinaldo);
			config.Property(t => t.PersonaContacto).HasMaxLength(50);
			config.Property(t => t.Autoridades).HasMaxLength(255);
			config.Property(t => t.CodRegimenAporte);
			config.Property(t => t.CodSituacionPago);
			config.Property(t => t.Liquidar);
			config.Property(t => t.Ficticia);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.RegimenAporte).WithMany(t => t.Empresas).HasForeignKey(t => t.CodRegimenAporte);
			config.HasOne(t => t.SituacionPago).WithMany(t => t.Empresas).HasForeignKey(t => t.CodSituacionPago);
		}

		/// <summary>Defines the mapping information for the entity 'EmpresaPago'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapEmpresaPago(EntityTypeBuilder<EmpresaPago> config)
		{
			config.ToTable("EmpresaPago");
			config.HasKey(t => t.EmpresaPagoId);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Importe);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.EmpresaPagoId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Empresa).WithMany(t => t.EmpresaPagos).HasForeignKey(t => t.CodEmpresa);
		}

		/// <summary>Defines the mapping information for the entity 'Especialidad'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapEspecialidad(EntityTypeBuilder<Especialidad> config)
		{
			config.ToTable("Especialidad");
			config.HasKey(t => t.CodEspecialidad);
			config.Property(t => t.CodEspecialidad);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'FormaPago'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapFormaPago(EntityTypeBuilder<FormaPago> config)
		{
			config.ToTable("FormaPago");
			config.HasKey(t => t.CodFormaPago);
			config.Property(t => t.CodFormaPago);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'FranjaIrpf'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapFranjaIrpf(EntityTypeBuilder<FranjaIrpf> config)
		{
			config.ToTable("FranjaIRPF");
			config.HasKey(t => t.Desde);
			config.Property(t => t.Desde);
			config.Property(t => t.Hasta);
			config.Property(t => t.Porcentaje);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Imp'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapImp(EntityTypeBuilder<Imp> config)
		{
			config.ToTable("IMP");
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Importe);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Imponible'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapImponible(EntityTypeBuilder<Imponible> config)
		{
			config.ToTable("Imponible");
			config.HasKey(t => t.ImponibleId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Fechaingreso);
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Concepto).HasMaxLength(3).IsRequired();
			config.Property(t => t.IdTrabaja);
			config.Property(t => t.DiasTrabajados);
			config.Property(t => t.Importe);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.AnioMes);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.ImponibleId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Trabaja).WithMany(t => t.Imponibles).HasForeignKey(t => t.IdTrabaja);
		}

		/// <summary>Defines the mapping information for the entity 'InformeEstadistico'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapInformeEstadistico(EntityTypeBuilder<InformeEstadistico> config)
		{
			config.ToTable("InformeEstadistico");
			config.HasKey(t => t.IdRpt);
			config.Property(t => t.IdRpt);
			config.Property(t => t.Grupo).HasMaxLength(50);
			config.Property(t => t.Orden);
			config.Property(t => t.TituloPantalla).HasMaxLength(255);
			config.Property(t => t.TituloRpt).HasMaxLength(255);
			config.Property(t => t.MesAnio);
			config.Property(t => t.Periodo);
			config.Property(t => t.Empresa);
			config.Property(t => t.Fecha);
			config.Property(t => t.GrupoEtario);
			config.Property(t => t.Comentario);
			config.Property(t => t.Patologia);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'LiquidacionBp'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapLiquidacionBp(EntityTypeBuilder<LiquidacionBp> config)
		{
			config.ToTable("Liquidacion_BPS");
			config.HasKey(t => t.LiquidacionBpsid);
			config.Property(t => t.LiquidacionBpsid).HasColumnName("LiquidacionBPSId").ValueGeneratedOnAdd();
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Nombre).HasColumnName("NOMBRE").HasMaxLength(255);
			config.Property(t => t.Apellido).HasColumnName("APELLIDO").HasMaxLength(255);
			config.Property(t => t.MontoTotal).HasColumnName("MONTO_TOTAL");
			config.Property(t => t.MesDeCargo).HasColumnName("MES_DE_CARGO");
			config.Property(t => t.NomEmpresa).HasColumnName("NOM_EMPRESA").HasMaxLength(255);
			config.Property(t => t.PctPorEmpresa).HasColumnName("PCT_POR_EMPRESA");
			config.Property(t => t.FechaPerDesde).HasColumnName("FECHA_PER_DESDE");
			config.Property(t => t.FechaPerHasta).HasColumnName("FECHA_PER_HASTA");
			config.Property(t => t.NEntrega).HasColumnName("N_ ENTREGA");
			config.Property(t => t.FechaDeEntrega).HasColumnName("FECHA_DE_ENTREGA");
			config.Property(t => t.Mes).HasColumnName("MES");
			config.Property(t => t.Anio).HasColumnName("ANIO");
			config.Property(t => t.Liquido).HasColumnName("LIQUIDO");
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'MaeFun'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapMaeFun(EntityTypeBuilder<MaeFun> config)
		{
			config.ToTable("MaeFun");
			config.HasKey(t => t.NroFun);
			config.Property(t => t.NroFun);
			config.Property(t => t.NroCuenta);
			config.Property(t => t.Apellido1).HasMaxLength(15).IsRequired();
			config.Property(t => t.Apellido2).HasMaxLength(15);
			config.Property(t => t.Nombre1).HasMaxLength(15).IsRequired();
			config.Property(t => t.Nombre2).HasMaxLength(15);
			config.Property(t => t.Cedula);
			config.Property(t => t.Nacionalidad);
			config.Property(t => t.FecNac);
			config.Property(t => t.EstCivil);
			config.Property(t => t.DirCalle).HasMaxLength(20);
			config.Property(t => t.DirPuerta).HasMaxLength(4);
			config.Property(t => t.DirBis).HasMaxLength(2);
			config.Property(t => t.DirPiso).HasMaxLength(2);
			config.Property(t => t.DirApto).HasMaxLength(4);
			config.Property(t => t.DirBloque).HasMaxLength(2);
			config.Property(t => t.DirLocal).HasMaxLength(30);
			config.Property(t => t.CodCargo);
			config.Property(t => t.DesCargo).HasMaxLength(25);
			config.Property(t => t.Telefono).HasMaxLength(8);
			config.Property(t => t.FecIngreso);
			config.Property(t => t.InfDbla);
			config.Property(t => t.FecInfDbla);
			config.Property(t => t.AsigCuenta);
			config.Property(t => t.FecAsigCta);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Moneda'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapMoneda(EntityTypeBuilder<Moneda> config)
		{
			config.ToTable("Moneda");
			config.HasKey(t => t.Simbolo);
			config.Property(t => t.Simbolo).HasColumnName("Moneda").HasMaxLength(3);
		}

		/// <summary>Defines the mapping information for the entity 'Mutualistum'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapMutualistum(EntityTypeBuilder<Mutualistum> config)
		{
			config.ToTable("Mutualista");
			config.HasKey(t => t.CodMutualista);
			config.Property(t => t.CodMutualista);
			config.Property(t => t.Nombre).HasMaxLength(50);
			config.Property(t => t.Direccion).HasMaxLength(50);
			config.Property(t => t.Telefono).HasMaxLength(50);
			config.Property(t => t.Fax).HasMaxLength(25);
			config.Property(t => t.Email).HasColumnName("EMail").HasMaxLength(25);
			config.Property(t => t.DiaPago);
			config.Property(t => t.CodFormaPago);
			config.Property(t => t.PersonaContacto).HasMaxLength(50);
			config.Property(t => t.Cuota);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.Ficticia);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.FormaPago).WithMany(t => t.Mutualista).HasForeignKey(t => t.CodFormaPago);
		}

		/// <summary>Defines the mapping information for the entity 'NoCargadoHl'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapNoCargadoHl(EntityTypeBuilder<NoCargadoHl> config)
		{
			config.ToTable("NoCargadoHL");
			config.HasKey(t => t.NoCargadoHlid);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Apellido1).HasMaxLength(50);
			config.Property(t => t.Apellido2).HasMaxLength(50);
			config.Property(t => t.Nombres).HasMaxLength(50);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.NoCargadoHlid).HasColumnName("NoCargadoHLId").ValueGeneratedOnAdd();
		}

		/// <summary>Defines the mapping information for the entity 'Parametro'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapParametro(EntityTypeBuilder<Parametro> config)
		{
			config.ToTable("Parametros");
			config.Property(t => t.Smn).HasColumnName("SMN");
			config.Property(t => t.TopeJubilatorio);
			config.Property(t => t.TopePrima);
			config.Property(t => t.Ur).HasColumnName("UR");
			config.Property(t => t.PctAdPreJub);
			config.Property(t => t.Bcp).HasColumnName("BCP");
			config.Property(t => t.TopeLiquidoBps).HasColumnName("TopeLiquidoBPS");
			config.Property(t => t.PctBps).HasColumnName("pctBPS");
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'Patologium'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapPatologium(EntityTypeBuilder<Patologium> config)
		{
			config.ToTable("Patologia");
			config.HasKey(t => t.CodPatologia);
			config.Property(t => t.CodPatologia);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'Prestacion'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapPrestacion(EntityTypeBuilder<Prestacion> config)
		{
			config.ToTable("Prestacion");
			config.HasKey(t => t.PrestacionId);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Fecha);
			config.Property(t => t.CodPrestacionTipo);
			config.Property(t => t.Moneda).HasMaxLength(3);
			config.Property(t => t.Importe);
			config.Property(t => t.Boleta);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.PrestacionId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Afiliado).WithMany(t => t.Prestacions).HasForeignKey(t => t.Ci);
			config.HasOne(t => t.Moneda1).WithMany(t => t.Prestacions).HasForeignKey(t => t.Moneda);
			config.HasOne(t => t.PrestacionTipo).WithMany(t => t.Prestacions).HasForeignKey(t => t.CodPrestacionTipo);
		}

		/// <summary>Defines the mapping information for the entity 'PrestacionTipo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapPrestacionTipo(EntityTypeBuilder<PrestacionTipo> config)
		{
			config.ToTable("PrestacionTipo");
			config.HasKey(t => t.CodPrestacionTipo);
			config.Property(t => t.CodPrestacionTipo);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.FechaVigencia);
			config.Property(t => t.ImporteTopeDisse).HasColumnName("ImporteTopeDISSE");
			config.Property(t => t.ImporteTopeCasemed).HasColumnName("ImporteTopeCASEMED");
			config.Property(t => t.PeriodoRenovacion);
			config.Property(t => t.Receta);
			config.Property(t => t.Obs);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'PrimaFallecimiento'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapPrimaFallecimiento(EntityTypeBuilder<PrimaFallecimiento> config)
		{
			config.ToTable("PrimaFallecimiento");
			config.HasKey(t => t.Ci);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.FechaFirma);
			config.Property(t => t.FechaFallecimiento);
			config.Property(t => t.Importe);
			config.Property(t => t.FechaPago);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Afiliado).WithOne(t => t.PrimaFallecimiento).HasForeignKey<PrimaFallecimiento>(t => t.Ci).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'RecetaDistancium'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapRecetaDistancium(EntityTypeBuilder<RecetaDistancium> config)
		{
			config.ToTable("RecetaDistancia");
			config.HasKey(t => t.CodRecetaDistancia);
			config.Property(t => t.CodRecetaDistancia).HasMaxLength(3);
			config.Property(t => t.Descrip).HasMaxLength(50);
		}

		/// <summary>Defines the mapping information for the entity 'Recetum'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapRecetum(EntityTypeBuilder<Recetum> config)
		{
			config.ToTable("Receta");
			config.HasKey(t => t.RecetaId);
			config.Property(t => t.RecetaId).ValueGeneratedOnAdd();
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Fecha);
			config.Property(t => t.CodPrestacionTipo);
			config.Property(t => t.CodRecetaDistancia).HasMaxLength(3).IsRequired();
			config.Property(t => t.EsfI).HasColumnName("Esf_I");
			config.Property(t => t.EsfD).HasColumnName("Esf_D");
			config.Property(t => t.CilI).HasColumnName("Cil_I");
			config.Property(t => t.CilD).HasColumnName("Cil_D");
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.PrestacionId);
			config.HasOne(t => t.Prestacion).WithMany(t => t.Receta).HasForeignKey(t => t.PrestacionId);
			config.HasOne(t => t.RecetaDistancium).WithMany(t => t.Receta).HasForeignKey(t => t.CodRecetaDistancia);
		}

		/// <summary>Defines the mapping information for the entity 'RegimenAporte'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapRegimenAporte(EntityTypeBuilder<RegimenAporte> config)
		{
			config.ToTable("RegimenAporte");
			config.HasKey(t => t.CodRegimenAporte);
			config.Property(t => t.CodRegimenAporte);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Porcentaje);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'RegimenJubilatorio'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapRegimenJubilatorio(EntityTypeBuilder<RegimenJubilatorio> config)
		{
			config.ToTable("RegimenJubilatorio");
			config.HasKey(t => t.CodRegimenJubilatorio);
			config.Property(t => t.CodRegimenJubilatorio);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'ReintegroMutual'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapReintegroMutual(EntityTypeBuilder<ReintegroMutual> config)
		{
			config.ToTable("ReintegroMutual");
			config.HasKey(t => t.ReintegroMutualId);
			config.Property(t => t.ReintegroMutualId).ValueGeneratedOnAdd();
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Fecha);
			config.Property(t => t.CodMutualista);
			config.Property(t => t.Importe);
			config.Property(t => t.Observaciones);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Afiliado).WithMany(t => t.ReintegroMutuals).HasForeignKey(t => t.Ci);
			config.HasOne(t => t.Mutualistum).WithMany(t => t.ReintegroMutuals).HasForeignKey(t => t.CodMutualista);
		}

		/// <summary>Defines the mapping information for the entity 'SalidaTipo'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSalidaTipo(EntityTypeBuilder<SalidaTipo> config)
		{
			config.ToTable("SalidaTipo");
			config.HasKey(t => t.CodSalidaTipo);
			config.Property(t => t.CodSalidaTipo);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'Seleccion'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSeleccion(EntityTypeBuilder<Seleccion> config)
		{
			config.ToTable("Seleccion");
			config.HasKey(t => t.SeleccionId);
			config.Property(t => t.SeleccionId).ValueGeneratedOnAdd();
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Form).HasMaxLength(255);
			config.Property(t => t.Nombre).HasMaxLength(255);
			config.Property(t => t.Txt);
			config.Property(t => t.System);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'SituacionMutual'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSituacionMutual(EntityTypeBuilder<SituacionMutual> config)
		{
			config.ToTable("SituacionMutual");
			config.HasKey(t => t.CodSituacionMutual);
			config.Property(t => t.CodSituacionMutual).HasMaxLength(2);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Pagar);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'SituacionPago'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSituacionPago(EntityTypeBuilder<SituacionPago> config)
		{
			config.ToTable("SituacionPago");
			config.HasKey(t => t.CodSituacionPago);
			config.Property(t => t.CodSituacionPago);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioCabezal'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioCabezal(EntityTypeBuilder<SubsidioCabezal> config)
		{
			config.ToTable("SubsidioCabezal");
			config.HasKey(t => t.IdSubsidio);
			config.Property(t => t.IdSubsidio).ValueGeneratedOnAdd();
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Liquidar);
			config.Property(t => t.ValorJornal);
			config.Property(t => t.Dias);
			config.Property(t => t.ImpNominal);
			config.Property(t => t.ImpAguinaldo);
			config.Property(t => t.ImpLiquido);
			config.Property(t => t.NroRecibo);
			config.Property(t => t.FechaPago);
			config.Property(t => t.CodBanco);
			config.Property(t => t.NroCuenta).HasMaxLength(50);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Afiliado).WithMany(t => t.SubsidioCabezals).HasForeignKey(t => t.Ci);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioCabezalBp'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioCabezalBp(EntityTypeBuilder<SubsidioCabezalBp> config)
		{
			config.ToTable("SubsidioCabezal_BPS");
			config.HasKey(t => t.IdSubsidio);
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.DiasBps).HasColumnName("DiasBPS");
			config.Property(t => t.LiquidoBps).HasColumnName("LiquidoBPS");
			config.Property(t => t.AguinaldoBps).HasColumnName("AguinaldoBPS");
			config.Property(t => t.LiquidoPagar);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.SubsidioCabezal).WithOne(t => t.SubsidioCabezalBp).HasForeignKey<SubsidioCabezalBp>(t => t.IdSubsidio).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioCabezalEmpresa'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioCabezalEmpresa(EntityTypeBuilder<SubsidioCabezalEmpresa> config)
		{
			config.ToTable("SubsidioCabezalEmpresa");
			config.HasKey(t => t.SubsidioCabezalempresaId);
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.ValorJornal);
			config.Property(t => t.Dias);
			config.Property(t => t.ImpNominal);
			config.Property(t => t.ImpAguinaldo);
			config.Property(t => t.ImpLiquido);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.SubsidioCabezalempresaId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Empresa).WithMany(t => t.SubsidioCabezalEmpresas).HasForeignKey(t => t.CodEmpresa);
			config.HasOne(t => t.SubsidioCabezal).WithMany(t => t.SubsidioCabezalEmpresas).HasForeignKey(t => t.IdSubsidio).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioEnfermedad'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioEnfermedad(EntityTypeBuilder<SubsidioEnfermedad> config)
		{
			config.ToTable("SubsidioEnfermedad");
			config.HasKey(t => t.SubsidioEnfermedadId);
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.FechaIni);
			config.Property(t => t.FechaFin);
			config.Property(t => t.FechaIniSubsidio);
			config.Property(t => t.FechaFinSubsidio);
			config.Property(t => t.NroLlamado);
			config.Property(t => t.Dias);
			config.Property(t => t.Importe);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.SubsidioEnfermedadId).ValueGeneratedOnAdd();
			config.HasOne(t => t.SubsidioCabezal).WithMany(t => t.SubsidioEnfermedads).HasForeignKey(t => t.IdSubsidio).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioImponible'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioImponible(EntityTypeBuilder<SubsidioImponible> config)
		{
			config.ToTable("SubsidioImponible");
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.Mes);
			config.Property(t => t.Anio);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Dias);
			config.Property(t => t.Importe);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.HasOne(t => t.Empresa).WithMany(t => t.SubsidioImponibles).HasForeignKey(t => t.CodEmpresa).OnDelete(DeleteBehavior.Cascade);
			config.HasOne(t => t.SubsidioCabezal).WithMany(t => t.SubsidioImponibles).HasForeignKey(t => t.IdSubsidio).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioItem'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioItem(EntityTypeBuilder<SubsidioItem> config)
		{
			config.ToTable("SubsidioItem");
			config.HasKey(t => t.SubsidioItemId);
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.CodSubsidioItemCod);
			config.Property(t => t.Importe);
			config.Property(t => t.AbiEmp);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.SubsidioItemId).ValueGeneratedOnAdd();
			config.HasOne(t => t.SubsidioCabezal).WithMany(t => t.SubsidioItems).HasForeignKey(t => t.IdSubsidio).OnDelete(DeleteBehavior.Cascade);
			config.HasOne(t => t.SubsidioItemCod).WithMany(t => t.SubsidioItems).HasForeignKey(t => t.CodSubsidioItemCod).OnDelete(DeleteBehavior.Cascade);
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioItemCod'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioItemCod(EntityTypeBuilder<SubsidioItemCod> config)
		{
			config.ToTable("SubsidioItemCod");
			config.HasKey(t => t.CodSubsidioItemCod);
			config.Property(t => t.CodSubsidioItemCod);
			config.Property(t => t.Descrip).HasMaxLength(50);
			config.Property(t => t.Tipo).HasMaxLength(1);
			config.Property(t => t.ValorTipo).HasMaxLength(50);
			config.Property(t => t.Signo);
			config.Property(t => t.Comparar);
			config.Property(t => t.CompararContra);
			config.Property(t => t.Valor);
			config.Property(t => t.TipoComp).HasMaxLength(1);
			config.Property(t => t.Operador).HasMaxLength(5);
			config.Property(t => t.ValorMin);
			config.Property(t => t.ValorMax);
			config.Property(t => t.Procesar);
			config.Property(t => t.FechaVigencia);
			config.Property(t => t.FechaBaja);
			config.Property(t => t.AperturaXempresa).HasColumnName("AperturaXEmpresa");
			config.Property(t => t.ModificaNominal);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioItemCodAfiliado'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioItemCodAfiliado(EntityTypeBuilder<SubsidioItemCodAfiliado> config)
		{
			config.ToTable("SubsidioItemCod_Afiliado");
			config.HasKey(t => t.SubItmCodAfiId);
			config.Property(t => t.SubItmCodAfiId).ValueGeneratedOnAdd();
			config.Property(t => t.CodSubsidioItemCod);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.Valor);
			config.Property(t => t.Vigencia);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
		}

		/// <summary>Defines the mapping information for the entity 'SubsidioItemEmpresa'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapSubsidioItemEmpresa(EntityTypeBuilder<SubsidioItemEmpresa> config)
		{
			config.ToTable("SubsidioItemEmpresa");
			config.HasKey(t => t.SubsidioItemEmpresaId);
			config.Property(t => t.IdSubsidio);
			config.Property(t => t.CodSubsidioItemCod);
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.Importe);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.Property(t => t.SsmaTimeStamp).HasColumnName("SSMA_TimeStamp").ValueGeneratedOnAddOrUpdate().IsRequired();
			config.Property(t => t.SubsidioItemEmpresaId).ValueGeneratedOnAdd();
			config.HasOne(t => t.Empresa).WithMany(t => t.SubsidioItemEmpresas).HasForeignKey(t => t.CodEmpresa);
		}

		/// <summary>Defines the mapping information for the entity 'Trabaja'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapTrabaja(EntityTypeBuilder<Trabaja> config)
		{
			config.ToTable("Trabaja");
			config.HasKey(t => t.IdTrabaja);
			config.Property(t => t.Ci).HasColumnName("CI");
			config.Property(t => t.CodEmpresa);
			config.Property(t => t.FechaIngreso);
			config.Property(t => t.FechaBaja);
			config.Property(t => t.CodBajaMotivo);
			config.Property(t => t.NroFichaEmpresa).HasMaxLength(20);
			config.Property(t => t.IdTrabaja).ValueGeneratedOnAdd();
			config.Property(t => t.FechaIngCasemed);
			config.Property(t => t.Usr).HasMaxLength(8);
			config.Property(t => t.Ts);
			config.HasOne(t => t.Afiliado).WithMany(t => t.Trabajas).HasForeignKey(t => t.Ci);
			config.HasOne(t => t.BajaMotivo).WithMany(t => t.Trabajas).HasForeignKey(t => t.CodBajaMotivo);
			config.HasOne(t => t.Empresa).WithMany(t => t.Trabajas).HasForeignKey(t => t.CodEmpresa);
		}

		/// <summary>Defines the mapping information for the entity 'XUsrParam'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapXUsrParam(EntityTypeBuilder<XUsrParam> config)
		{
			config.ToTable("xUsrParam");
			config.HasKey(t => t.IdUsuario);
			config.Property(t => t.Login).HasColumnName("login").HasMaxLength(8).IsRequired();
			config.Property(t => t.Clave).HasColumnName("clave").HasMaxLength(100).IsRequired();
			config.Property(t => t.Orden).HasColumnName("orden");
			config.Property(t => t.Value1).HasColumnName("value1").HasMaxLength(255);
			config.Property(t => t.Value2).HasColumnName("value2").HasMaxLength(255);
			config.Property(t => t.Value3).HasColumnName("value3").HasMaxLength(255);
			config.Property(t => t.Value4).HasColumnName("value4").HasMaxLength(255);
			config.Property(t => t.Value5).HasColumnName("value5").HasMaxLength(255);
			config.Property(t => t.IdUsuario).ValueGeneratedOnAdd();
		}
	}


	/// <summary>Extensions class for extension methods used in the model builder code</summary>
	internal static partial class SgpaNewModelBuilderExtensions
	{
		private static readonly string READONLY_ANNOTATION = "custom:readonly";

		/// <summary>Extension method which is used by the context class to determine whether an entity is readonly</summary>
		/// <typeparam name="TEntity">The type of the entity.</typeparam>
		/// <param name="builder">The entity type builder object to augment.</param>
		/// <returns>the passed in entity type builder</returns>
		internal static EntityTypeBuilder<TEntity> IsReadOnly<TEntity>(this EntityTypeBuilder<TEntity> builder)
			where TEntity : class
		{
			builder.HasAnnotation(READONLY_ANNOTATION, true);
			return builder;
		}
		
		/// <summary>Determines whether the passed in entity type has the readonly annotation set.
		/// </summary>
		/// <param name="entity">The entity type to check.</param>
		/// <returns>true if the entity type is marked as read-only, false otherwise</returns>
		public static bool IsReadOnly(this IEntityType entity)
		{
			var annotation = entity.FindAnnotation(READONLY_ANNOTATION);
			return annotation != null && (bool)annotation.Value;
		}
	}
}

